// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/auth0/auth0connection/v1/stack_outputs.proto

package auth0connectionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Auth0ConnectionStackOutputs contains the outputs from an Auth0 Connection deployment.
// These outputs provide essential identifiers and information for integrating
// the connection with applications and monitoring its configuration.
//
// https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#attributes-reference
// https://www.pulumi.com/registry/packages/auth0/api-docs/connection/#outputs
type Auth0ConnectionStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of the Auth0 connection.
	// This is the primary identifier used in Auth0 APIs and Management Dashboard.
	// Format: "con_" followed by a unique string (e.g., "con_0000000000000001").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the unique name of the connection within the Auth0 tenant.
	// This name is used in authentication URLs and API calls.
	// It is automatically generated from metadata.name or can be customized.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// strategy is the identity provider strategy type.
	// Reflects the connection type configured in the spec.
	// Examples: "auth0", "google-oauth2", "samlp", "oidc", "waad"
	Strategy string `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// is_enabled indicates whether the connection is currently enabled.
	// A disabled connection cannot be used for authentication.
	IsEnabled string `protobuf:"bytes,4,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	// provisioning_ticket_url is the URL used for self-service connection setup.
	// Only available for certain enterprise connections (like SAML or OIDC).
	// Users can visit this URL to complete connection configuration.
	ProvisioningTicketUrl string `protobuf:"bytes,5,opt,name=provisioning_ticket_url,json=provisioningTicketUrl,proto3" json:"provisioning_ticket_url,omitempty"`
	// callback_url is the Auth0 callback URL for this connection.
	// For social and enterprise connections, this URL must be registered
	// with the identity provider.
	// Format: https://{tenant}.auth0.com/login/callback
	CallbackUrl string `protobuf:"bytes,6,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	// metadata_url is the SAML metadata URL for this connection.
	// Only available for SAML connections.
	// Identity Providers can use this to configure the Service Provider.
	// Format: https://{tenant}.auth0.com/samlp/metadata/{connection_name}
	MetadataUrl string `protobuf:"bytes,7,opt,name=metadata_url,json=metadataUrl,proto3" json:"metadata_url,omitempty"`
	// entity_id is the SAML Service Provider Entity ID.
	// Only available for SAML connections.
	// This is the unique identifier Auth0 uses as a SAML SP.
	// Format: urn:auth0:{tenant}:{connection_name}
	EntityId string `protobuf:"bytes,8,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// enabled_client_ids is the list of Auth0 application client IDs
	// that can use this connection.
	EnabledClientIds []string `protobuf:"bytes,9,rep,name=enabled_client_ids,json=enabledClientIds,proto3" json:"enabled_client_ids,omitempty"`
	// realms is the list of realms/domains associated with this connection.
	// Used for identifier-first authentication flows.
	Realms        []string `protobuf:"bytes,10,rep,name=realms,proto3" json:"realms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth0ConnectionStackOutputs) Reset() {
	*x = Auth0ConnectionStackOutputs{}
	mi := &file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth0ConnectionStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth0ConnectionStackOutputs) ProtoMessage() {}

func (x *Auth0ConnectionStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth0ConnectionStackOutputs.ProtoReflect.Descriptor instead.
func (*Auth0ConnectionStackOutputs) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *Auth0ConnectionStackOutputs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetIsEnabled() string {
	if x != nil {
		return x.IsEnabled
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetProvisioningTicketUrl() string {
	if x != nil {
		return x.ProvisioningTicketUrl
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetMetadataUrl() string {
	if x != nil {
		return x.MetadataUrl
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Auth0ConnectionStackOutputs) GetEnabledClientIds() []string {
	if x != nil {
		return x.EnabledClientIds
	}
	return nil
}

func (x *Auth0ConnectionStackOutputs) GetRealms() []string {
	if x != nil {
		return x.Realms
	}
	return nil
}

var File_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"Iorg/project_planton/provider/auth0/auth0connection/v1/stack_outputs.proto\x125org.project_planton.provider.auth0.auth0connection.v1\"\xdd\x02\n" +
	"\x1bAuth0ConnectionStackOutputs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x04 \x01(\tR\tisEnabled\x126\n" +
	"\x17provisioning_ticket_url\x18\x05 \x01(\tR\x15provisioningTicketUrl\x12!\n" +
	"\fcallback_url\x18\x06 \x01(\tR\vcallbackUrl\x12!\n" +
	"\fmetadata_url\x18\a \x01(\tR\vmetadataUrl\x12\x1b\n" +
	"\tentity_id\x18\b \x01(\tR\bentityId\x12,\n" +
	"\x12enabled_client_ids\x18\t \x03(\tR\x10enabledClientIds\x12\x16\n" +
	"\x06realms\x18\n" +
	" \x03(\tR\x06realmsB\xb8\x03\n" +
	"9com.org.project_planton.provider.auth0.auth0connection.v1B\x11StackOutputsProtoP\x01Zqgithub.com/plantonhq/project-planton/apis/org/project_planton/provider/auth0/auth0connection/v1;auth0connectionv1\xa2\x02\x05OPPAA\xaa\x024Org.ProjectPlanton.Provider.Auth0.Auth0connection.V1\xca\x024Org\\ProjectPlanton\\Provider\\Auth0\\Auth0connection\\V1\xe2\x02@Org\\ProjectPlanton\\Provider\\Auth0\\Auth0connection\\V1\\GPBMetadata\xea\x029Org::ProjectPlanton::Provider::Auth0::Auth0connection::V1b\x06proto3"

var (
	file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDescData []byte
)

func file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDesc), len(file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDesc)))
	})
	return file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDescData
}

var file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_goTypes = []any{
	(*Auth0ConnectionStackOutputs)(nil), // 0: org.project_planton.provider.auth0.auth0connection.v1.Auth0ConnectionStackOutputs
}
var file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_init() }
func file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_init() {
	if File_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDesc), len(file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto = out.File
	file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_goTypes = nil
	file_org_project_planton_provider_auth0_auth0connection_v1_stack_outputs_proto_depIdxs = nil
}
