apiVersion: digital-ocean.project-planton.org/v1
kind: DigitalOceanDatabaseCluster
metadata:
  name: first-db
spec:
  clusterName: first-db                 # human‑readable identifier
  engine: postgres                          # postgres | mysql | redis | mongodb
  engineVersion: "14"                       # major or major.minor
  region: blr1                              # DigitalOceanRegion enum value
  sizeSlug: db-s-2vcpu-4gb                  # any valid managed‑DB size slug
  nodeCount: 1                         # 1‑3
  vpc:
    value: b5648f9e-a28a-4760-bb87-b2fad07ae295                        # UUID or StringValueOrRef to DigitalOceanVpc
  storageGib: 10                           # optional custom storage
  enablePublicConnectivity: true           # true to allow public access
