# Auth0 Resource Server Test Manifest
# This file is used for testing the Auth0ResourceServer deployment component
#
# Prerequisites:
# 1. Set the following environment variables:
#    - AUTH0_DOMAIN: Your Auth0 tenant domain (e.g., your-tenant.auth0.com)
#    - AUTH0_CLIENT_ID: M2M application client ID
#    - AUTH0_CLIENT_SECRET: M2M application client secret
#
# 2. The M2M application must have these scopes:
#    - create:resource_servers
#    - read:resource_servers
#    - update:resource_servers
#    - delete:resource_servers

apiVersion: auth0.project-planton.org/v1
kind: Auth0ResourceServer
metadata:
  name: test-api
  org: test-org
  env: development
  labels:
    purpose: testing
spec:
  # Required: API identifier (audience)
  identifier: https://api.test.project-planton.org/

  # Optional: Friendly display name
  name: Test API

  # Token configuration
  signing_alg: RS256
  token_lifetime: 86400         # 24 hours
  token_lifetime_for_web: 7200  # 2 hours

  # Access control
  allow_offline_access: true
  skip_consent_for_verifiable_first_party_clients: true
  enforce_policies: true
  token_dialect: access_token_authz

  # API Scopes/Permissions
  scopes:
    - name: read:items
      description: Read access to items
    - name: write:items
      description: Create and update items
    - name: delete:items
      description: Delete items
    - name: admin:all
      description: Full administrative access
