apiVersion: aws.project-planton.org/v1
kind: AwsLambda
metadata:
  name: awslambda-demo
spec:
  function_name: awslambda-demo
  role_arn: arn:aws:iam::123456789012:role/service-role/awslambda-demo-role
  code_source_type: CODE_SOURCE_TYPE_S3
  runtime: nodejs18.x
  handler: index.handler
  s3:
    bucket: example-artifacts
    key: lambda/hello.zip
  memory_mb: 128
  timeout_seconds: 10
  # reserved_concurrency: -1
  # environment: {}
  # subnets: []
  # security_groups: []
  # architecture: X86_64
  # layer_arns: []
  # kms_key_arn: ""
