apiVersion: aws.project-planton.org/v1
kind: AwsLambda
metadata:
  name: awslambda-demo
spec:
  function_name: awslambda-demo
  description: Example Lambda function
  role_arn:
    value: arn:aws:iam::123456789012:role/lambda-basic-exec
  code_source_type: CODE_SOURCE_TYPE_S3
  runtime: nodejs18.x
  handler: index.handler
  s3:
    bucket: my-bucket
    key: lambda/hello.zip
  memory_mb: 128
  timeout_seconds: 10
  reserved_concurrency: -1
  environment:
    EXAMPLE: "true"
  architecture: X86_64
  # layer_arns:
  #   - arn:aws:lambda:us-east-1:123456789012:layer:example:1
  # subnets:
  #   - value: subnet-abc123
  # security_groups:
  #   - value: sg-abc123
  # kms_key_arn:
  #   value: arn:aws:kms:us-east-1:123456789012:key/abc123
