# Production-Ready AWS ECR Repository Example
# This manifest demonstrates best practices for a production ECR repository
# with security, cost control, and compliance features enabled.
#
# Usage:
#   planton apply -f manifest.yaml

apiVersion: aws.project-planton.org/v1
kind: AwsEcrRepo
metadata:
  name: production-ecr-repo
  # These will be populated by the system:
  # org: my-organization
  # env: production
  # id: ecr-xxxxxxxxxxxxxx
spec:
  # Repository name - can be namespaced for organization
  repository_name: my-company/production-api

  # Image immutability - CRITICAL for production stability
  # When true, prevents tag overwrites (e.g., can't overwrite "v1.0" tag)
  # Recommendation: Always true for production
  image_immutable: true

  # Image scanning - CRITICAL for security
  # Automatically scans pushed images for CVE vulnerabilities
  # Recommendation: Always true (default)
  scan_on_push: true

  # Encryption configuration
  # Options: "AES256" (AWS-managed) or "KMS" (customer-managed)
  # Use KMS when compliance requires auditable key management
  encryption_type: AES256
  # kms_key_id: arn:aws:kms:us-east-1:123456789012:key/prod-ecr-key

  # Force delete protection - Prevents accidental deletion
  # When false, cannot delete repository with images
  # Recommendation: false for production (default)
  force_delete: false

  # Lifecycle policy - CRITICAL for cost control
  # Without lifecycle policies, storage costs grow indefinitely
  lifecycle_policy:
    # Remove untagged images after 1 day (intermediate build layers)
    # Recommendation: 1-14 days depending on build frequency
    expire_untagged_after_days: 1

    # Keep only the last 100 images, expire older ones
    # Recommendation: 30-100 for production depending on deployment cadence
    max_image_count: 100

---

# Development Environment Example
# More lenient configuration for development/testing

apiVersion: aws.project-planton.org/v1
kind: AwsEcrRepo
metadata:
  name: development-ecr-repo
spec:
  repository_name: my-company/dev-api

  # Allow mutable tags in dev for flexibility
  image_immutable: false

  # Still scan for security
  scan_on_push: true

  # AES256 is sufficient for dev
  encryption_type: AES256

  # Allow force delete in dev for easier cleanup
  force_delete: true

  # More aggressive cleanup for dev
  lifecycle_policy:
    expire_untagged_after_days: 3
    max_image_count: 20

---

# Minimal Example
# Simplest configuration with secure defaults

apiVersion: aws.project-planton.org/v1
kind: AwsEcrRepo
metadata:
  name: minimal-ecr-repo
spec:
  # Only repository_name is required
  # All other fields use secure defaults:
  # - image_immutable: false (can be overridden to true)
  # - scan_on_push: true (security default)
  # - encryption_type: AES256 (secure default)
  # - force_delete: false (safety default)
  repository_name: my-company/simple-service

---

# Compliance Example
# Configuration for regulated environments (HIPAA, PCI-DSS)

apiVersion: aws.project-planton.org/v1
kind: AwsEcrRepo
metadata:
  name: compliance-ecr-repo
spec:
  repository_name: my-company/compliant-service

  # Immutable tags for audit trail
  image_immutable: true

  # Mandatory scanning
  scan_on_push: true

  # Customer-managed encryption for key lifecycle control
  encryption_type: KMS
  kms_key_id: arn:aws:kms:us-east-1:123456789012:key/compliance-key

  # Prevent accidental deletion
  force_delete: false

  # Longer retention for compliance
  lifecycle_policy:
    expire_untagged_after_days: 30
    max_image_count: 365  # Keep one year of images

