apiVersion: aws.project-planton.org/v1
kind: AwsSecurityGroup
metadata:
  name: http-https-from-anywhere
spec:
  vpcId: "vpc-12345abcde"
  description: "Security group allowing inbound HTTP and HTTPS."
  ingressRules:
    - protocol: "tcp"
      fromPort: 80
      toPort: 80
      ipv4Cidrs:
        - "0.0.0.0/0"
      ruleDescription: "Allow HTTP from anywhere."
    - protocol: "tcp"
      fromPort: 443
      toPort: 443
      ipv4Cidrs:
        - "0.0.0.0/0"
      ruleDescription: "Allow HTTPS from anywhere."
