apiVersion: aws.project-planton.org/v1
kind: AwsSecurityGroup
metadata:
  name: ssh-from-anywhere
spec:
  vpcId: "vpc-12345abcde"
  name: "my-ssh-sg"
  description: "Security group allowing inbound SSH."
  ingressRules:
    - protocol: "tcp"
      fromPort: 22
      toPort: 22
      ipv4Cidrs:
        - "0.0.0.0/0"
      ruleDescription: "Allow SSH from anywhere."
