apiVersion: aws.project-planton.org/v1
kind: AwsSecurityGroup
metadata:
  name: ssh-from-anywhere
spec:
  vpcId: vpc-0e6cca66639175a98
  description: Security group allowing inbound SSH.
  ingress:
    - protocol: "tcp"
      fromPort: 22
      toPort: 22
      ipv4Cidrs:
        - "0.0.0.0/0"
      description: Allow SSH from anywhere.
