apiVersion: digital-ocean.project-planton.org/v1
kind: DigitalOceanFirewall
metadata:
  name: first-firewall                 # Kubernetes object name
spec:
  name: first-firewall                 # DigitalOcean firewall name
  inboundRules:
    - protocol: tcp
      portRange: "80"
      sourceAddresses:
        - "0.0.0.0/0"                # allow HTTP from anywhere
    - protocol: tcp
      portRange: "443"
      sourceAddresses:
        - "0.0.0.0/0"                # allow HTTPS from anywhere
  outboundRules:
    - protocol: tcp
      portRange: "1-65535"
      destinationAddresses:
        - "0.0.0.0/0"                # allow all outbound traffic
  dropletIds: []
  tags:
    - project-planton
