apiVersion: digital-ocean.project-planton.org/v1
kind: DigitalOceanVolume
metadata:
  name: first-volume
spec:
  volumeName: data-volume-01          # lowercase letters, numbers, hyphens
  description: "Block storage for PostgreSQL"
  region: nyc3                        # any valid DigitalOceanRegion enum value
  sizeGib: 100                        # 1 – 16000 GiB
  filesystemType: EXT4                # EXT4 | XFS | NONE
  snapshotId: ""                      # leave blank if not using a snapshot
  tags:
    - project-planton
    - env-staging
