apiVersion: gcp.project-planton.org/v1
kind: GcpProject
metadata:
  name: my-sample-project
spec:
  # Attach this project under an organization or folder (one or the other).
  # If using an organization, specify orgId, e.g. "123456789012".
  # If using a folder, specify folderId, e.g. "345678901234".
  orgId: "123456789012"
  folderId: ""

  # Billing account (alphanumeric string). E.g. "01ABCD-23EFGH-45IJKL"
  billingAccountId: "0123AB-4567CD-89EFGH"

  # Optional K/V labels for cost governance, environment, etc.
  labels:
    environment: dev
    costCenter: "fin-dev"
    team: devops

  # True => disable default network (autoCreateNetwork=false). Common security practice.
  disableDefaultNetwork: true

  # List of GCP service APIs to enable in this project.
  enabledApis:
    - compute.googleapis.com
    - iam.googleapis.com

  # (Optional) If set, assigns roles/owner to this user/group/SA on the new project.
  # e.g. "group:devops@example.com" or "user:alice@example.com"
  ownerMember: "group:devops@example.com"
