---
apiVersion: aws.project-planton.org/v1
kind: AwsEcsService
metadata:
  name: "{{ values.service_name }}"
spec:
  alb:
    arn:
      valueFrom:
        kind: AwsAlb
        name: "{{ values.env }}-ecs-services-alb"
        fieldPath: status.outputs.loadBalancerArn
    enabled: true
    hostname: "{{ values.service_name }}.{{ values.load_balancer_domain_name }}"
    routingType: hostname
    listenerPort: {{ 443 if values.httpsEnabled | bool else 80 }}
    listenerPriority: 100
  clusterArn:
    valueFrom:
      kind: AwsEcsCluster
      name: "{{ values.env }}-ecs-cluster"
      fieldPath: status.outputs.clusterArn
  container:
    cpu: 256
    env:
      variables:
        SERVICE_NAME: "{{ values.service_name }}"
    image:
      repo: nginx
      tag: latest
    memory: 512
    port: 80
    replicas: 1
  iam:
    taskExecutionRoleArn:
      valueFrom:
        kind: AwsIamRole
        name: "{{ values.env }}-ecs-task-execution-role"
        fieldPath: status.outputs.roleArn
  network:
    securityGroups:
      - valueFrom:
          kind: AwsSecurityGroup
          name: "{{ values.env }}-http-ingress-and-all-egress"
          fieldPath: status.outputs.securityGroupId
    subnets:
      - valueFrom:
          kind: AwsVpc
          name: "{{ values.env }}-vpc"
          fieldPath: status.outputs.privateSubnets.[0].id
