// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: project/planton/provider/gcp/gcpproject/v1/stack_outputs.proto

package gcpprojectv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GcpProjectStackOutputs surfaces key attributes of the newly-provisioned
// Google Cloud project. These values are stored in the resource.status
// for downstream modules (e.g. networking, CI/CD) to consume.
type GcpProjectStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name of the project (mirrors spec.name).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Immutable project ID (mirrors spec.project_id).
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Numeric project number assigned by Google.
	ProjectNumber string `protobuf:"bytes,3,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpProjectStackOutputs) Reset() {
	*x = GcpProjectStackOutputs{}
	mi := &file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpProjectStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpProjectStackOutputs) ProtoMessage() {}

func (x *GcpProjectStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpProjectStackOutputs.ProtoReflect.Descriptor instead.
func (*GcpProjectStackOutputs) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *GcpProjectStackOutputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GcpProjectStackOutputs) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GcpProjectStackOutputs) GetProjectNumber() string {
	if x != nil {
		return x.ProjectNumber
	}
	return ""
}

var File_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	">project/planton/provider/gcp/gcpproject/v1/stack_outputs.proto\x12*project.planton.provider.gcp.gcpproject.v1\"r\n" +
	"\x16GcpProjectStackOutputs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12%\n" +
	"\x0eproject_number\x18\x03 \x01(\tR\rprojectNumberB\xfb\x02\n" +
	".com.project.planton.provider.gcp.gcpproject.v1B\x11StackOutputsProtoP\x01Zggithub.com/project-planton/project-planton/apis/project/planton/provider/gcp/gcpproject/v1;gcpprojectv1\xa2\x02\x05PPPGG\xaa\x02*Project.Planton.Provider.Gcp.Gcpproject.V1\xca\x02*Project\\Planton\\Provider\\Gcp\\Gcpproject\\V1\xe2\x026Project\\Planton\\Provider\\Gcp\\Gcpproject\\V1\\GPBMetadata\xea\x02/Project::Planton::Provider::Gcp::Gcpproject::V1b\x06proto3"

var (
	file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDescData []byte
)

func file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDesc), len(file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDesc)))
	})
	return file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDescData
}

var file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_goTypes = []any{
	(*GcpProjectStackOutputs)(nil), // 0: project.planton.provider.gcp.gcpproject.v1.GcpProjectStackOutputs
}
var file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_init() }
func file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_init() {
	if File_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDesc), len(file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto = out.File
	file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_goTypes = nil
	file_project_planton_provider_gcp_gcpproject_v1_stack_outputs_proto_depIdxs = nil
}
