# =============================================================================
# Release Orchestrator
# =============================================================================
# Single entry point for all release workflows. Triggers on semantic version
# tags (v*) and orchestrates the release of CLI, Docker image, website, and
# all Pulumi module binaries.
#
# Architecture:
#   1. CLI job runs first (GoReleaser creates the GitHub Release)
#   2. App and Website jobs run in parallel (independent of each other)
#   3. Pulumi modules job runs after CLI completes (depends on release existing)
#
# Trigger: git tag v0.1.0 && git push origin v0.1.0
# =============================================================================

name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  # ============================================================================
  # CLI Release - Creates the GitHub Release
  # ============================================================================
  cli:
    uses: ./.github/workflows/release/cli.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

  # ============================================================================
  # Docker App Release - Runs in parallel
  # ============================================================================
  app:
    uses: ./.github/workflows/release/app.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ============================================================================
  # Website Release - Runs in parallel
  # ============================================================================
  website:
    uses: ./.github/workflows/release/website.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ============================================================================
  # Pulumi Modules - All providers (runs after CLI creates release)
  # ============================================================================
  pulumi-modules:
    needs: cli
    uses: ./.github/workflows/release/pulumi-modules.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
