apiVersion: kubernetes.project-planton.org/v1
kind: TemporalKubernetes
metadata:
  name: project-planton-test-temporal-with-pg
spec:
  database:
    backend: postgresql
    externalDatabase:
      host: db-temporal.postgres-app-prod-temporal.svc.cluster.local
      port: 5432
      username: postgres
      password: LkvoiPyCiYkyvXNfFRcn96vuNCFH10ufV5jnGnOucRDKpk0xglqUnX3a0FPFdcfd
  ingress:
    isEnabled: false
