apiVersion: digital-ocean.project-planton.org/v1
kind: DigitalOceanLoadBalancer
metadata:
  name: first-lb
spec:
  loadBalancerName: first-lb       # Must be unique per DigitalOcean account
  region: blr1                    # Any valid DigitalOceanRegion slug (e.g., nyc3, sfo3, fra1)
  vpc:
    value: b5648f9e-a28a-4760-bb87-b2fad07ae295                        # UUID or StringValueOrRef to DigitalOceanVpc
  forwardingRules: # One or more rules
    - entryPort: 80
      entryProtocol: http
      targetPort: 80
      targetProtocol: http
#    - entryPort: 443
#      entryProtocol: https
#      targetPort: 443
#      targetProtocol: https
  healthCheck: # Optional; recommended for HTTP/HTTPS traffic
    port: 80
    protocol: http
    path: /health
    checkIntervalSec: 10          # Defaults to 10 s if omitted (per proto hint)
  dropletTag: web                 # Attach all Droplets with this tag (mutually exclusive with dropletIds)
  enableStickySessions: false     # Set true to enable cookie‑based session affinity
