// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/digitalocean/digitaloceankubernetesnodepool/v1/stack_input.proto

package digitaloceankubernetesnodepoolv1

import (
	digitalocean "github.com/plantonhq/project-planton/apis/org/project_planton/provider/digitalocean"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// digital-ocean-kubernetes-node-pool stack-input
type DigitalOceanKubernetesNodePoolStackInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target cloud-resource
	Target *DigitalOceanKubernetesNodePool `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// provider-config
	ProviderConfig *digitalocean.DigitalOceanProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DigitalOceanKubernetesNodePoolStackInput) Reset() {
	*x = DigitalOceanKubernetesNodePoolStackInput{}
	mi := &file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalOceanKubernetesNodePoolStackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalOceanKubernetesNodePoolStackInput) ProtoMessage() {}

func (x *DigitalOceanKubernetesNodePoolStackInput) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalOceanKubernetesNodePoolStackInput.ProtoReflect.Descriptor instead.
func (*DigitalOceanKubernetesNodePoolStackInput) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDescGZIP(), []int{0}
}

func (x *DigitalOceanKubernetesNodePoolStackInput) GetTarget() *DigitalOceanKubernetesNodePool {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DigitalOceanKubernetesNodePoolStackInput) GetProviderConfig() *digitalocean.DigitalOceanProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

var File_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDesc = "" +
	"\n" +
	"]org/project_planton/provider/digitalocean/digitaloceankubernetesnodepool/v1/stack_input.proto\x12Korg.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1\x1aUorg/project_planton/provider/digitalocean/digitaloceankubernetesnodepool/v1/api.proto\x1a8org/project_planton/provider/digitalocean/provider.proto\"\xa0\x02\n" +
	"(DigitalOceanKubernetesNodePoolStackInput\x12\x83\x01\n" +
	"\x06target\x18\x01 \x01(\v2k.org.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1.DigitalOceanKubernetesNodePoolR\x06target\x12n\n" +
	"\x0fprovider_config\x18\x02 \x01(\v2E.org.project_planton.provider.digitalocean.DigitalOceanProviderConfigR\x0eproviderConfigB\xca\x04\n" +
	"Ocom.org.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1B\x0fStackInputProtoP\x01Z\x96\x01github.com/plantonhq/project-planton/apis/org/project_planton/provider/digitalocean/digitaloceankubernetesnodepool/v1;digitaloceankubernetesnodepoolv1\xa2\x02\x05OPPDD\xaa\x02JOrg.ProjectPlanton.Provider.Digitalocean.Digitaloceankubernetesnodepool.V1\xca\x02JOrg\\ProjectPlanton\\Provider\\Digitalocean\\Digitaloceankubernetesnodepool\\V1\xe2\x02VOrg\\ProjectPlanton\\Provider\\Digitalocean\\Digitaloceankubernetesnodepool\\V1\\GPBMetadata\xea\x02OOrg::ProjectPlanton::Provider::Digitalocean::Digitaloceankubernetesnodepool::V1b\x06proto3"

var (
	file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDescData []byte
)

func file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDesc), len(file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDesc)))
	})
	return file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDescData
}

var file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_goTypes = []any{
	(*DigitalOceanKubernetesNodePoolStackInput)(nil), // 0: org.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1.DigitalOceanKubernetesNodePoolStackInput
	(*DigitalOceanKubernetesNodePool)(nil),           // 1: org.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1.DigitalOceanKubernetesNodePool
	(*digitalocean.DigitalOceanProviderConfig)(nil),  // 2: org.project_planton.provider.digitalocean.DigitalOceanProviderConfig
}
var file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_depIdxs = []int32{
	1, // 0: org.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1.DigitalOceanKubernetesNodePoolStackInput.target:type_name -> org.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1.DigitalOceanKubernetesNodePool
	2, // 1: org.project_planton.provider.digitalocean.digitaloceankubernetesnodepool.v1.DigitalOceanKubernetesNodePoolStackInput.provider_config:type_name -> org.project_planton.provider.digitalocean.DigitalOceanProviderConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_init()
}
func file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_init() {
	if File_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto != nil {
		return
	}
	file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDesc), len(file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto = out.File
	file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_goTypes = nil
	file_org_project_planton_provider_digitalocean_digitaloceankubernetesnodepool_v1_stack_input_proto_depIdxs = nil
}
