apiVersion: kubernetes.project.planton/v1
kind: JenkinsKubernetes
metadata:
  name: test-jenkins-server
spec:
  containerResources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  helmValues:
    key-2: value-2
    key-3: value-3
  ingress:
    isEnabled: true
    dnsDomain: example.com
