// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/aws/awsdynamodb/v1/api.proto

package awsdynamodbv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/project-planton/apis/org/project_planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsDynamodb is the Kubernetes-style resource envelope for a DynamoDB table.
type AwsDynamodb struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	ApiVersion    string                        `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                        `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *AwsDynamodbSpec              `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *AwsDynamodbStatus            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsDynamodb) Reset() {
	*x = AwsDynamodb{}
	mi := &file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsDynamodb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsDynamodb) ProtoMessage() {}

func (x *AwsDynamodb) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsDynamodb.ProtoReflect.Descriptor instead.
func (*AwsDynamodb) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AwsDynamodb) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AwsDynamodb) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AwsDynamodb) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AwsDynamodb) GetSpec() *AwsDynamodbSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AwsDynamodb) GetStatus() *AwsDynamodbStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AwsDynamodbStatus captures lifecycle, audit, job linkage, and observable outputs.
type AwsDynamodbStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *AwsDynamodbStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsDynamodbStatus) Reset() {
	*x = AwsDynamodbStatus{}
	mi := &file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsDynamodbStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsDynamodbStatus) ProtoMessage() {}

func (x *AwsDynamodbStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsDynamodbStatus.ProtoReflect.Descriptor instead.
func (*AwsDynamodbStatus) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AwsDynamodbStatus) GetOutputs() *AwsDynamodbStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_project_planton_provider_aws_awsdynamodb_v1_api_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDesc = "" +
	"\n" +
	"9org/project_planton/provider/aws/awsdynamodb/v1/api.proto\x12/org.project_planton.provider.aws.awsdynamodb.v1\x1a\x1bbuf/validate/validate.proto\x1a:org/project_planton/provider/aws/awsdynamodb/v1/spec.proto\x1aCorg/project_planton/provider/aws/awsdynamodb/v1/stack_outputs.proto\x1a)org/project_planton/shared/metadata.proto\"\x8a\x03\n" +
	"\vAwsDynamodb\x12B\n" +
	"\vapi_version\x18\x01 \x01(\tB!\xbaH\x1er\x1c\n" +
	"\x1aaws.project-planton.org/v1R\n" +
	"apiVersion\x12&\n" +
	"\x04kind\x18\x02 \x01(\tB\x12\xbaH\x0fr\r\n" +
	"\vAwsDynamodbR\x04kind\x12U\n" +
	"\bmetadata\x18\x03 \x01(\v21.org.project_planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12\\\n" +
	"\x04spec\x18\x04 \x01(\v2@.org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12Z\n" +
	"\x06status\x18\x05 \x01(\v2B.org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbStatusR\x06status\"w\n" +
	"\x11AwsDynamodbStatus\x12b\n" +
	"\aoutputs\x18\x01 \x01(\v2H.org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbStackOutputsR\aoutputsB\x87\x03\n" +
	"3com.org.project_planton.provider.aws.awsdynamodb.v1B\bApiProtoP\x01Zggithub.com/plantonhq/project-planton/apis/org/project_planton/provider/aws/awsdynamodb/v1;awsdynamodbv1\xa2\x02\x05OPPAA\xaa\x02.Org.ProjectPlanton.Provider.Aws.Awsdynamodb.V1\xca\x02.Org\\ProjectPlanton\\Provider\\Aws\\Awsdynamodb\\V1\xe2\x02:Org\\ProjectPlanton\\Provider\\Aws\\Awsdynamodb\\V1\\GPBMetadata\xea\x023Org::ProjectPlanton::Provider::Aws::Awsdynamodb::V1b\x06proto3"

var (
	file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescData []byte
)

func file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDesc), len(file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDesc)))
	})
	return file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDescData
}

var file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_goTypes = []any{
	(*AwsDynamodb)(nil),                  // 0: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodb
	(*AwsDynamodbStatus)(nil),            // 1: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbStatus
	(*shared.CloudResourceMetadata)(nil), // 2: org.project_planton.shared.CloudResourceMetadata
	(*AwsDynamodbSpec)(nil),              // 3: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbSpec
	(*AwsDynamodbStackOutputs)(nil),      // 4: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbStackOutputs
}
var file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_depIdxs = []int32{
	2, // 0: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodb.metadata:type_name -> org.project_planton.shared.CloudResourceMetadata
	3, // 1: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodb.spec:type_name -> org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbSpec
	1, // 2: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodb.status:type_name -> org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbStatus
	4, // 3: org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbStatus.outputs:type_name -> org.project_planton.provider.aws.awsdynamodb.v1.AwsDynamodbStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_init() }
func file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_init() {
	if File_org_project_planton_provider_aws_awsdynamodb_v1_api_proto != nil {
		return
	}
	file_org_project_planton_provider_aws_awsdynamodb_v1_spec_proto_init()
	file_org_project_planton_provider_aws_awsdynamodb_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDesc), len(file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_aws_awsdynamodb_v1_api_proto = out.File
	file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_goTypes = nil
	file_org_project_planton_provider_aws_awsdynamodb_v1_api_proto_depIdxs = nil
}
