// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/kubernetes/workload/solrkubernetes/v1/api.proto

package solrkubernetesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/project-planton/project-planton/apis/org/project_planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// solr-kubernetes
type SolrKubernetes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *SolrKubernetesSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *SolrKubernetesStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolrKubernetes) Reset() {
	*x = SolrKubernetes{}
	mi := &file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolrKubernetes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolrKubernetes) ProtoMessage() {}

func (x *SolrKubernetes) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolrKubernetes.ProtoReflect.Descriptor instead.
func (*SolrKubernetes) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *SolrKubernetes) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SolrKubernetes) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SolrKubernetes) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SolrKubernetes) GetSpec() *SolrKubernetesSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *SolrKubernetes) GetStatus() *SolrKubernetesStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// solr-kubernetes status
type SolrKubernetesStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *SolrKubernetesStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolrKubernetesStatus) Reset() {
	*x = SolrKubernetesStatus{}
	mi := &file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolrKubernetesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolrKubernetesStatus) ProtoMessage() {}

func (x *SolrKubernetesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolrKubernetesStatus.ProtoReflect.Descriptor instead.
func (*SolrKubernetesStatus) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *SolrKubernetesStatus) GetOutputs() *SolrKubernetesStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDesc = "" +
	"\n" +
	"Lorg/project_planton/provider/kubernetes/workload/solrkubernetes/v1/api.proto\x12Borg.project_planton.provider.kubernetes.workload.solrkubernetes.v1\x1a\x1bbuf/validate/validate.proto\x1aMorg/project_planton/provider/kubernetes/workload/solrkubernetes/v1/spec.proto\x1aVorg/project_planton/provider/kubernetes/workload/solrkubernetes/v1/stack_outputs.proto\x1a)org/project_planton/shared/metadata.proto\"\xc3\x03\n" +
	"\x0eSolrKubernetes\x12I\n" +
	"\vapi_version\x18\x01 \x01(\tB(\xbaH%r#\n" +
	"!kubernetes.project-planton.org/v1R\n" +
	"apiVersion\x12)\n" +
	"\x04kind\x18\x02 \x01(\tB\x15\xbaH\x12r\x10\n" +
	"\x0eSolrKubernetesR\x04kind\x12U\n" +
	"\bmetadata\x18\x03 \x01(\v21.org.project_planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12r\n" +
	"\x04spec\x18\x04 \x01(\v2V.org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12p\n" +
	"\x06status\x18\x05 \x01(\v2X.org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesStatusR\x06status\"\x90\x01\n" +
	"\x14SolrKubernetesStatus\x12x\n" +
	"\aoutputs\x18\x01 \x01(\v2^.org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesStackOutputsR\aoutputsB\x85\x04\n" +
	"Fcom.org.project_planton.provider.kubernetes.workload.solrkubernetes.v1B\bApiProtoP\x01Z\x83\x01github.com/project-planton/project-planton/apis/org/project_planton/provider/kubernetes/workload/solrkubernetes/v1;solrkubernetesv1\xa2\x02\x06OPPKWS\xaa\x02AOrg.ProjectPlanton.Provider.Kubernetes.Workload.Solrkubernetes.V1\xca\x02AOrg\\ProjectPlanton\\Provider\\Kubernetes\\Workload\\Solrkubernetes\\V1\xe2\x02MOrg\\ProjectPlanton\\Provider\\Kubernetes\\Workload\\Solrkubernetes\\V1\\GPBMetadata\xea\x02GOrg::ProjectPlanton::Provider::Kubernetes::Workload::Solrkubernetes::V1b\x06proto3"

var (
	file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescData []byte
)

func file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDesc), len(file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDesc)))
	})
	return file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDescData
}

var file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_goTypes = []any{
	(*SolrKubernetes)(nil),               // 0: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetes
	(*SolrKubernetesStatus)(nil),         // 1: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesStatus
	(*shared.CloudResourceMetadata)(nil), // 2: org.project_planton.shared.CloudResourceMetadata
	(*SolrKubernetesSpec)(nil),           // 3: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesSpec
	(*SolrKubernetesStackOutputs)(nil),   // 4: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesStackOutputs
}
var file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_depIdxs = []int32{
	2, // 0: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetes.metadata:type_name -> org.project_planton.shared.CloudResourceMetadata
	3, // 1: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetes.spec:type_name -> org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesSpec
	1, // 2: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetes.status:type_name -> org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesStatus
	4, // 3: org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesStatus.outputs:type_name -> org.project_planton.provider.kubernetes.workload.solrkubernetes.v1.SolrKubernetesStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_init() }
func file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_init() {
	if File_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto != nil {
		return
	}
	file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_spec_proto_init()
	file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDesc), len(file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto = out.File
	file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_goTypes = nil
	file_org_project_planton_provider_kubernetes_workload_solrkubernetes_v1_api_proto_depIdxs = nil
}
