// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project-planton/provider/gcp/gcpcloudsql/v1/api.proto

package gcpcloudsqlv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/project-planton/project-planton/apis/org/project-planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gcp-cloud-sql
type GcpCloudSql struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *GcpCloudSqlSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *GcpCloudSqlStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpCloudSql) Reset() {
	*x = GcpCloudSql{}
	mi := &file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpCloudSql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpCloudSql) ProtoMessage() {}

func (x *GcpCloudSql) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpCloudSql.ProtoReflect.Descriptor instead.
func (*GcpCloudSql) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GcpCloudSql) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GcpCloudSql) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GcpCloudSql) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GcpCloudSql) GetSpec() *GcpCloudSqlSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GcpCloudSql) GetStatus() *GcpCloudSqlStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// gcp-cloud-sql status
type GcpCloudSqlStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *GcpCloudSqlStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpCloudSqlStatus) Reset() {
	*x = GcpCloudSqlStatus{}
	mi := &file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpCloudSqlStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpCloudSqlStatus) ProtoMessage() {}

func (x *GcpCloudSqlStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpCloudSqlStatus.ProtoReflect.Descriptor instead.
func (*GcpCloudSqlStatus) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GcpCloudSqlStatus) GetOutputs() *GcpCloudSqlStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDesc = "" +
	"\n" +
	"9org/project-planton/provider/gcp/gcpcloudsql/v1/api.proto\x12/org.project_planton.provider.gcp.gcpcloudsql.v1\x1a\x1bbuf/validate/validate.proto\x1a:org/project-planton/provider/gcp/gcpcloudsql/v1/spec.proto\x1aCorg/project-planton/provider/gcp/gcpcloudsql/v1/stack_outputs.proto\x1a)org/project-planton/shared/metadata.proto\"\x8a\x03\n" +
	"\vGcpCloudSql\x12B\n" +
	"\vapi_version\x18\x01 \x01(\tB!\xbaH\x1er\x1c\n" +
	"\x1agcp.project-planton.org/v1R\n" +
	"apiVersion\x12&\n" +
	"\x04kind\x18\x02 \x01(\tB\x12\xbaH\x0fr\r\n" +
	"\vGcpCloudSqlR\x04kind\x12U\n" +
	"\bmetadata\x18\x03 \x01(\v21.org.project_planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12\\\n" +
	"\x04spec\x18\x04 \x01(\v2@.org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12Z\n" +
	"\x06status\x18\x05 \x01(\v2B.org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlStatusR\x06status\"w\n" +
	"\x11GcpCloudSqlStatus\x12b\n" +
	"\aoutputs\x18\x01 \x01(\v2H.org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlStackOutputsR\aoutputsB\x8d\x03\n" +
	"3com.org.project_planton.provider.gcp.gcpcloudsql.v1B\bApiProtoP\x01Zmgithub.com/project-planton/project-planton/apis/org/project-planton/provider/gcp/gcpcloudsql/v1;gcpcloudsqlv1\xa2\x02\x05OPPGG\xaa\x02.Org.ProjectPlanton.Provider.Gcp.Gcpcloudsql.V1\xca\x02.Org\\ProjectPlanton\\Provider\\Gcp\\Gcpcloudsql\\V1\xe2\x02:Org\\ProjectPlanton\\Provider\\Gcp\\Gcpcloudsql\\V1\\GPBMetadata\xea\x023Org::ProjectPlanton::Provider::Gcp::Gcpcloudsql::V1b\x06proto3"

var (
	file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescData []byte
)

func file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDesc), len(file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDesc)))
	})
	return file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDescData
}

var file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_goTypes = []any{
	(*GcpCloudSql)(nil),                  // 0: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSql
	(*GcpCloudSqlStatus)(nil),            // 1: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlStatus
	(*shared.CloudResourceMetadata)(nil), // 2: org.project_planton.shared.CloudResourceMetadata
	(*GcpCloudSqlSpec)(nil),              // 3: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlSpec
	(*GcpCloudSqlStackOutputs)(nil),      // 4: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlStackOutputs
}
var file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_depIdxs = []int32{
	2, // 0: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSql.metadata:type_name -> org.project_planton.shared.CloudResourceMetadata
	3, // 1: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSql.spec:type_name -> org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlSpec
	1, // 2: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSql.status:type_name -> org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlStatus
	4, // 3: org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlStatus.outputs:type_name -> org.project_planton.provider.gcp.gcpcloudsql.v1.GcpCloudSqlStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_init() }
func file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_init() {
	if File_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto != nil {
		return
	}
	file_org_project_planton_provider_gcp_gcpcloudsql_v1_spec_proto_init()
	file_org_project_planton_provider_gcp_gcpcloudsql_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDesc), len(file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto = out.File
	file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_goTypes = nil
	file_org_project_planton_provider_gcp_gcpcloudsql_v1_api_proto_depIdxs = nil
}
