apiVersion: kubernetes.project.planton/v1
kind: SolrKubernetes
metadata:
  name: test-solr-cloud
spec:
  ingress:
    dnsDomain: example.com
    isEnabled: true
  solrContainer:
    diskSize: 1Gi
    image:
      repo: solr
      tag: 8.7.0
    replicas: 1
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 250Mi
  config: {}
  zookeeperContainer:
    diskSize: 1Gi
    replicas: 1
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 250Mi
