// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/kubernetes/kubernetestekton/v1/api.proto

package kubernetestektonv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/project-planton/project-planton/apis/org/project_planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KubernetesTekton deploys Tekton Pipelines and Dashboard on Kubernetes using official release manifests.
//
// This is the manifest-based deployment approach (as opposed to the operator-based KubernetesTektonOperator).
// It's simpler to understand and debug, and gives direct control over configuration.
type KubernetesTekton struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *KubernetesTektonSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *KubernetesTektonStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesTekton) Reset() {
	*x = KubernetesTekton{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesTekton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesTekton) ProtoMessage() {}

func (x *KubernetesTekton) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesTekton.ProtoReflect.Descriptor instead.
func (*KubernetesTekton) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesTekton) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *KubernetesTekton) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubernetesTekton) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *KubernetesTekton) GetSpec() *KubernetesTektonSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *KubernetesTekton) GetStatus() *KubernetesTektonStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// KubernetesTektonStatus represents the deployment status of the Tekton components.
type KubernetesTektonStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs from the IaC deployment
	Outputs       *KubernetesTektonStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesTektonStatus) Reset() {
	*x = KubernetesTektonStatus{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesTektonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesTektonStatus) ProtoMessage() {}

func (x *KubernetesTektonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesTektonStatus.ProtoReflect.Descriptor instead.
func (*KubernetesTektonStatus) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesTektonStatus) GetOutputs() *KubernetesTektonStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDesc = "" +
	"\n" +
	"Eorg/project_planton/provider/kubernetes/kubernetestekton/v1/api.proto\x12;org.project_planton.provider.kubernetes.kubernetestekton.v1\x1a\x1bbuf/validate/validate.proto\x1aForg/project_planton/provider/kubernetes/kubernetestekton/v1/spec.proto\x1aOorg/project_planton/provider/kubernetes/kubernetestekton/v1/stack_outputs.proto\x1a)org/project_planton/shared/metadata.proto\"\xbd\x03\n" +
	"\x10KubernetesTekton\x12I\n" +
	"\vapi_version\x18\x01 \x01(\tB(\xbaH%r#\n" +
	"!kubernetes.project-planton.org/v1R\n" +
	"apiVersion\x12+\n" +
	"\x04kind\x18\x02 \x01(\tB\x17\xbaH\x14r\x12\n" +
	"\x10KubernetesTektonR\x04kind\x12U\n" +
	"\bmetadata\x18\x03 \x01(\v21.org.project_planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12m\n" +
	"\x04spec\x18\x04 \x01(\v2Q.org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12k\n" +
	"\x06status\x18\x05 \x01(\v2S.org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonStatusR\x06status\"\x8d\x01\n" +
	"\x16KubernetesTektonStatus\x12s\n" +
	"\aoutputs\x18\x01 \x01(\v2Y.org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonStackOutputsR\aoutputsB\xda\x03\n" +
	"?com.org.project_planton.provider.kubernetes.kubernetestekton.v1B\bApiProtoP\x01Z~github.com/project-planton/project-planton/apis/org/project_planton/provider/kubernetes/kubernetestekton/v1;kubernetestektonv1\xa2\x02\x05OPPKK\xaa\x02:Org.ProjectPlanton.Provider.Kubernetes.Kubernetestekton.V1\xca\x02:Org\\ProjectPlanton\\Provider\\Kubernetes\\Kubernetestekton\\V1\xe2\x02FOrg\\ProjectPlanton\\Provider\\Kubernetes\\Kubernetestekton\\V1\\GPBMetadata\xea\x02?Org::ProjectPlanton::Provider::Kubernetes::Kubernetestekton::V1b\x06proto3"

var (
	file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescData []byte
)

func file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDesc), len(file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDesc)))
	})
	return file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDescData
}

var file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_goTypes = []any{
	(*KubernetesTekton)(nil),             // 0: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTekton
	(*KubernetesTektonStatus)(nil),       // 1: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonStatus
	(*shared.CloudResourceMetadata)(nil), // 2: org.project_planton.shared.CloudResourceMetadata
	(*KubernetesTektonSpec)(nil),         // 3: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonSpec
	(*KubernetesTektonStackOutputs)(nil), // 4: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonStackOutputs
}
var file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_depIdxs = []int32{
	2, // 0: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTekton.metadata:type_name -> org.project_planton.shared.CloudResourceMetadata
	3, // 1: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTekton.spec:type_name -> org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonSpec
	1, // 2: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTekton.status:type_name -> org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonStatus
	4, // 3: org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonStatus.outputs:type_name -> org.project_planton.provider.kubernetes.kubernetestekton.v1.KubernetesTektonStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_init() }
func file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_init() {
	if File_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto != nil {
		return
	}
	file_org_project_planton_provider_kubernetes_kubernetestekton_v1_spec_proto_init()
	file_org_project_planton_provider_kubernetes_kubernetestekton_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDesc), len(file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto = out.File
	file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_goTypes = nil
	file_org_project_planton_provider_kubernetes_kubernetestekton_v1_api_proto_depIdxs = nil
}
