// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/app/credential/v1/command.proto

package credentialv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_org_project_planton_app_credential_v1_command_proto protoreflect.FileDescriptor

const file_org_project_planton_app_credential_v1_command_proto_rawDesc = "" +
	"\n" +
	"3org/project_planton/app/credential/v1/command.proto\x12!org.project_planton.credential.v1\x1a.org/project_planton/app/credential/v1/io.proto2\xa9\x03\n" +
	"\x1bCredentialCommandController\x12\x81\x01\n" +
	"\x06Create\x12:.org.project_planton.credential.v1.CreateCredentialRequest\x1a;.org.project_planton.credential.v1.CreateCredentialResponse\x12\x81\x01\n" +
	"\x06Update\x12:.org.project_planton.credential.v1.UpdateCredentialRequest\x1a;.org.project_planton.credential.v1.UpdateCredentialResponse\x12\x81\x01\n" +
	"\x06Delete\x12:.org.project_planton.credential.v1.DeleteCredentialRequest\x1a;.org.project_planton.credential.v1.DeleteCredentialResponseB\xbc\x02\n" +
	"%com.org.project_planton.credential.v1B\fCommandProtoP\x01Zbgithub.com/project-planton/project-planton/apis/org/project_planton/app/credential/v1;credentialv1\xa2\x02\x03OPC\xaa\x02 Org.ProjectPlanton.Credential.V1\xca\x02 Org\\ProjectPlanton\\Credential\\V1\xe2\x02,Org\\ProjectPlanton\\Credential\\V1\\GPBMetadata\xea\x02#Org::ProjectPlanton::Credential::V1b\x06proto3"

var file_org_project_planton_app_credential_v1_command_proto_goTypes = []any{
	(*CreateCredentialRequest)(nil),  // 0: org.project_planton.credential.v1.CreateCredentialRequest
	(*UpdateCredentialRequest)(nil),  // 1: org.project_planton.credential.v1.UpdateCredentialRequest
	(*DeleteCredentialRequest)(nil),  // 2: org.project_planton.credential.v1.DeleteCredentialRequest
	(*CreateCredentialResponse)(nil), // 3: org.project_planton.credential.v1.CreateCredentialResponse
	(*UpdateCredentialResponse)(nil), // 4: org.project_planton.credential.v1.UpdateCredentialResponse
	(*DeleteCredentialResponse)(nil), // 5: org.project_planton.credential.v1.DeleteCredentialResponse
}
var file_org_project_planton_app_credential_v1_command_proto_depIdxs = []int32{
	0, // 0: org.project_planton.credential.v1.CredentialCommandController.Create:input_type -> org.project_planton.credential.v1.CreateCredentialRequest
	1, // 1: org.project_planton.credential.v1.CredentialCommandController.Update:input_type -> org.project_planton.credential.v1.UpdateCredentialRequest
	2, // 2: org.project_planton.credential.v1.CredentialCommandController.Delete:input_type -> org.project_planton.credential.v1.DeleteCredentialRequest
	3, // 3: org.project_planton.credential.v1.CredentialCommandController.Create:output_type -> org.project_planton.credential.v1.CreateCredentialResponse
	4, // 4: org.project_planton.credential.v1.CredentialCommandController.Update:output_type -> org.project_planton.credential.v1.UpdateCredentialResponse
	5, // 5: org.project_planton.credential.v1.CredentialCommandController.Delete:output_type -> org.project_planton.credential.v1.DeleteCredentialResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_project_planton_app_credential_v1_command_proto_init() }
func file_org_project_planton_app_credential_v1_command_proto_init() {
	if File_org_project_planton_app_credential_v1_command_proto != nil {
		return
	}
	file_org_project_planton_app_credential_v1_io_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_app_credential_v1_command_proto_rawDesc), len(file_org_project_planton_app_credential_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_project_planton_app_credential_v1_command_proto_goTypes,
		DependencyIndexes: file_org_project_planton_app_credential_v1_command_proto_depIdxs,
	}.Build()
	File_org_project_planton_app_credential_v1_command_proto = out.File
	file_org_project_planton_app_credential_v1_command_proto_goTypes = nil
	file_org_project_planton_app_credential_v1_command_proto_depIdxs = nil
}
