// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/openfga/openfgaauthorizationmodel/v1/spec.proto

package openfgaauthorizationmodelv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenFgaAuthorizationModelSpec defines the configuration for an OpenFGA Authorization Model.
//
// An authorization model defines the types, relations, and conditions that govern access control
// within an OpenFGA store. Each store can have multiple authorization models, with each new model
// being a complete replacement (not a patch) of the type definitions.
//
// The model is specified in JSON format and includes:
// - Type definitions: Define object types and their relations
// - Conditions (optional): Define dynamic conditions for access decisions
//
// IMPORTANT: Authorization models are immutable in OpenFGA. Creating a new model creates a new
// version. The model_json change will trigger a replacement (new model ID).
//
// IMPORTANT: OpenFGA only has a Terraform provider - there is no Pulumi provider available.
// This component must use Terraform/Tofu as the provisioner.
//
// Reference:
// - Terraform: https://registry.terraform.io/providers/openfga/openfga/latest/docs/resources/authorization_model
// - OpenFGA Docs: https://openfga.dev/docs/concepts#what-is-an-authorization-model
type OpenFgaAuthorizationModelSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// store_id is the unique identifier of the OpenFGA store where this model will be created.
	//
	// This ID is obtained from an OpenFgaStore deployment or from an existing store.
	// The store must exist before creating an authorization model.
	//
	// Note: The store_id is immutable - changing it requires replacing the model.
	//
	// Example: "01HXYZ..."
	StoreId string `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// model_json is the authorization model definition in JSON format.
	//
	// The JSON must conform to the OpenFGA authorization model schema and include:
	// - schema_version: The schema version (e.g., "1.1")
	// - type_definitions: Array of type definitions with name, relations, and metadata
	// - conditions (optional): Map of conditions for dynamic access decisions
	//
	// Note: The model is immutable - changing it requires replacing the model (new ID).
	//
	// Tip: Use the openfga_authorization_model_document data source in Terraform to convert
	// DSL format to JSON, or use the OpenFGA CLI to validate models before deployment.
	//
	// Example:
	//
	//	{
	//	  "schema_version": "1.1",
	//	  "type_definitions": [
	//	    {
	//	      "type": "user",
	//	      "relations": {}
	//	    },
	//	    {
	//	      "type": "document",
	//	      "relations": {
	//	        "viewer": {
	//	          "this": {}
	//	        },
	//	        "editor": {
	//	          "this": {}
	//	        },
	//	        "owner": {
	//	          "this": {}
	//	        }
	//	      },
	//	      "metadata": {
	//	        "relations": {
	//	          "viewer": {"directly_related_user_types": [{"type": "user"}]},
	//	          "editor": {"directly_related_user_types": [{"type": "user"}]},
	//	          "owner": {"directly_related_user_types": [{"type": "user"}]}
	//	        }
	//	      }
	//	    }
	//	  ]
	//	}
	ModelJson     string `protobuf:"bytes,2,opt,name=model_json,json=modelJson,proto3" json:"model_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFgaAuthorizationModelSpec) Reset() {
	*x = OpenFgaAuthorizationModelSpec{}
	mi := &file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFgaAuthorizationModelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFgaAuthorizationModelSpec) ProtoMessage() {}

func (x *OpenFgaAuthorizationModelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFgaAuthorizationModelSpec.ProtoReflect.Descriptor instead.
func (*OpenFgaAuthorizationModelSpec) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *OpenFgaAuthorizationModelSpec) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *OpenFgaAuthorizationModelSpec) GetModelJson() string {
	if x != nil {
		return x.ModelJson
	}
	return ""
}

var File_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDesc = "" +
	"\n" +
	"Lorg/project_planton/provider/openfga/openfgaauthorizationmodel/v1/spec.proto\x12Aorg.project_planton.provider.openfga.openfgaauthorizationmodel.v1\x1a\x1bbuf/validate/validate.proto\"i\n" +
	"\x1dOpenFgaAuthorizationModelSpec\x12!\n" +
	"\bstore_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\astoreId\x12%\n" +
	"\n" +
	"model_json\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tmodelJsonB\x83\x04\n" +
	"Ecom.org.project_planton.provider.openfga.openfgaauthorizationmodel.v1B\tSpecProtoP\x01Z\x87\x01github.com/plantonhq/project-planton/apis/org/project_planton/provider/openfga/openfgaauthorizationmodel/v1;openfgaauthorizationmodelv1\xa2\x02\x05OPPOO\xaa\x02@Org.ProjectPlanton.Provider.Openfga.Openfgaauthorizationmodel.V1\xca\x02@Org\\ProjectPlanton\\Provider\\Openfga\\Openfgaauthorizationmodel\\V1\xe2\x02LOrg\\ProjectPlanton\\Provider\\Openfga\\Openfgaauthorizationmodel\\V1\\GPBMetadata\xea\x02EOrg::ProjectPlanton::Provider::Openfga::Openfgaauthorizationmodel::V1b\x06proto3"

var (
	file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDescData []byte
)

func file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDesc), len(file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDesc)))
	})
	return file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDescData
}

var file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_goTypes = []any{
	(*OpenFgaAuthorizationModelSpec)(nil), // 0: org.project_planton.provider.openfga.openfgaauthorizationmodel.v1.OpenFgaAuthorizationModelSpec
}
var file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_init() }
func file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_init() {
	if File_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDesc), len(file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto = out.File
	file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_goTypes = nil
	file_org_project_planton_provider_openfga_openfgaauthorizationmodel_v1_spec_proto_depIdxs = nil
}
