{% if values.certManagerEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: CertManagerKubernetes
metadata:
  name: {{ values.cluster_name }}-cert-manager
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.elasticOperatorEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: ElasticOperatorKubernetes
metadata:
  name: {{ values.cluster_name }}-elastic-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.externalDnsEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: ExternalDnsKubernetes
metadata:
  name: {{ values.cluster_name }}-external-dns
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.externalSecretsEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: ExternalSecretsKubernetes
metadata:
  name: {{ values.cluster_name }}-external-secrets
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.ingressNginxEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: IngressNginxKubernetes
metadata:
  name: {{ values.cluster_name }}-ingress-nginx
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.istioEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: IstioKubernetes
metadata:
  name: {{ values.cluster_name }}-istio-ingress
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.kafkaOperatorEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KafkaOperatorKubernetes
metadata:
  name: {{ values.cluster_name }}-kafka-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.postgresOperatorEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: PostgresOperatorKubernetes
metadata:
  name: {{ values.cluster_name }}-postgres-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}

  {% if values.solrOperatorEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: SolrOperatorKubernetes
metadata:
  name: {{ values.cluster_name }}-solr-operator
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeClusterCore
      clusterName: "{{ values.cluster_name }}"
  {% endif %}
