# Minimal YAML for deploying an Aurora MySQL 8.0 cluster.
# Comments explain each field. Adjust values as needed for your environment.
apiVersion: aws.project-planton.org/v1
kind: AwsRdsCluster
metadata:
  # The name of this RDS cluster resource
  name: test-aws-rds-cluster

spec:
  # Aurora MySQL engine (vs. plain "mysql" for regular RDS MySQL)
  engine: aurora-mysql

  # Aurora MySQL 8.0 version
  engineVersion: "8.0"

  # Provisioned means a normal Aurora cluster (not serverless).
  # Use "serverless" if you want Aurora Serverless v1
  engineMode: provisioned

  # Valid DB parameter group family for Aurora MySQL 8.0
  clusterFamily: aurora-mysql8.0

  # DB instance class for Aurora MySQL (ensure it's valid in your region)
  instanceType: db.t3.medium

  # Number of instances to create in the cluster
  clusterSize: 1

  # Flag to allow a publicly accessible endpoint (not recommended for production)
  isPubliclyAccessible: true

  # Tells AWS to manage the master password via Secrets Manager
  manageMasterUserPassword: true

  # Master DB username (AWS will generate the password)
  masterUser: master

  # Only relevant if engineMode is set to "serverless"
  scalingConfiguration:
    maxCapacity: 16
    minCapacity: 2
    timeoutAction: RollbackCapacityChange
