params:
# ─── Network ──────────────────────────────────────────────────────────
- name: availability_zone_1
  description: Primary AZ
  value: us-east-1a

- name: availability_zone_2
  description: Secondary AZ
  value: us-east-1b

- name: vpc_cidr
  description: VPC CIDR block
  value: 10.0.0.0/16

- name: subnet_size
  description: /NN mask for each subnet
  value: "24"

# ─── Cluster core ─────────────────────────────────────────────────────
- name: cluster_name
  description: EKS cluster name
  value: eks-demo

- name: cluster_version
  description: Kubernetes version (e.g. 1.29)
  value: "1.29"

- name: disable_public_endpoint
  description: true → private endpoint
  type: bool
  value: true

- name: public_access_cidr
  description: Allowed CIDR if public endpoint enabled
  value: 0.0.0.0/0

- name: enable_control_plane_logs
  description: Enable all control‑plane logs
  type: bool
  value: true

# ─── Node‑group ───────────────────────────────────────────────────────
- name: node_group_name
  description: Managed node‑group name
  value: default-ng

- name: node_instance_type
  description: EC2 instance type
  value: t3.medium

- name: node_capacity_type
  description: on_demand | spot
  value: on_demand

- name: node_disk_size_gb
  description: Root disk (GiB)
  value: "100"

- name: node_min_size
  description: Autoscaler minimum
  value: "2"

- name: node_max_size
  description: Autoscaler maximum
  value: "5"

- name: node_desired_size
  description: Desired nodes
  value: "3"

- name: node_ssh_key_name
  description: EC2 KeyPair name (blank to disable SSH)
  value: ""

# ─── Route 53 & ACM Cert (optional) ───────────────────────────────────
- name: create_hosted_zone
  description: true → create Route 53 public zone
  type: bool
  value: false

- name: domain_name
  description: Apex domain managed in Route 53 (e.g. example.com)
  value: example.com

# ─── KMS secrets encryption ───────────────────────────────────────────
- name: enable_kms_encryption
  description: true → create CMK for secrets
  type: bool
  value: true

# ─── Kubernetes add‑ons ───────────────────────────────────────────────
- name: certManagerEnabled
  type: bool
  value: true
- name: elasticOperatorEnabled
  type: bool
  value: true
- name: externalDnsEnabled
  type: bool
  value: true
- name: externalSecretsEnabled
  type: bool
  value: true
- name: ingressNginxEnabled
  type: bool
  value: true
- name: istioEnabled
  type: bool
  value: true
- name: kafkaOperatorEnabled
  type: bool
  value: true
- name: postgresOperatorEnabled
  type: bool
  value: true
- name: solrOperatorEnabled
  type: bool
  value: true
