apiVersion: kubernetes.project-planton.org/v1
kind: MongodbKubernetes
metadata:
  name: test-mongo-database
spec:
  container:
    replicas: 1
    resources:
      limits:
        cpu: 2000m
        memory: 3Gi
      requests:
        cpu: 250m
        memory: 250Mi
    persistenceEnabled: true
    diskSize: 8Gi
  ingress:
    enabled: true
    hostname: test-mongo-database.example.com
