// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/azure/azurenatgateway/v1/spec.proto

package azurenatgatewayv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/project-planton/project-planton/apis/org/project_planton/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Azure NAT Gateway spec defines configuration for an Azure NAT Gateway resource.
type AzureNatGatewaySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the subnet to attach this NAT Gateway to (usually an existing Azure Subnet).
	// Defaults to referencing an AzureSubnet resource’s ID output.
	SubnetId *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// Idle timeout in minutes for TCP connections through the NAT Gateway.
	// Defaults to 4 if not set. Valid range: 4 to 120 (inclusive).
	IdleTimeoutMinutes *int32 `protobuf:"varint,2,opt,name=idle_timeout_minutes,json=idleTimeoutMinutes,proto3,oneof" json:"idle_timeout_minutes,omitempty"`
	// Optional prefix length for allocating a Public IP Prefix for this NAT Gateway.
	// If set (allowed values 28–31), a Public IP Prefix of /<prefix_length> is created instead of a single IP.
	PublicIpPrefixLength *int32 `protobuf:"varint,3,opt,name=public_ip_prefix_length,json=publicIpPrefixLength,proto3,oneof" json:"public_ip_prefix_length,omitempty"`
	// Optional tags to assign to the NAT Gateway resource.
	Tags          map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureNatGatewaySpec) Reset() {
	*x = AzureNatGatewaySpec{}
	mi := &file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureNatGatewaySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureNatGatewaySpec) ProtoMessage() {}

func (x *AzureNatGatewaySpec) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureNatGatewaySpec.ProtoReflect.Descriptor instead.
func (*AzureNatGatewaySpec) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AzureNatGatewaySpec) GetSubnetId() *v1.StringValueOrRef {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

func (x *AzureNatGatewaySpec) GetIdleTimeoutMinutes() int32 {
	if x != nil && x.IdleTimeoutMinutes != nil {
		return *x.IdleTimeoutMinutes
	}
	return 0
}

func (x *AzureNatGatewaySpec) GetPublicIpPrefixLength() int32 {
	if x != nil && x.PublicIpPrefixLength != nil {
		return *x.PublicIpPrefixLength
	}
	return 0
}

func (x *AzureNatGatewaySpec) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDesc = "" +
	"\n" +
	"@org/project_planton/provider/azure/azurenatgateway/v1/spec.proto\x125org.project_planton.provider.azure.azurenatgateway.v1\x1a\x1bbuf/validate/validate.proto\x1a:org/project_planton/shared/foreignkey/v1/foreign_key.proto\"\xff\x03\n" +
	"\x13AzureNatGatewaySpec\x12\x86\x01\n" +
	"\tsubnet_id\x18\x01 \x01(\v2:.org.project_planton.shared.foreignkey.v1.StringValueOrRefB-\xbaH\x03\xc8\x01\x01\x88\xd4a\x95\x03\x92\xd4a\x1estatus.outputs.nodes_subnet_idR\bsubnetId\x12@\n" +
	"\x14idle_timeout_minutes\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18x(\x04H\x00R\x12idleTimeoutMinutes\x88\x01\x01\x12E\n" +
	"\x17public_ip_prefix_length\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x1f(\x1cH\x01R\x14publicIpPrefixLength\x88\x01\x01\x12h\n" +
	"\x04tags\x18\x04 \x03(\v2T.org.project_planton.provider.azure.azurenatgateway.v1.AzureNatGatewaySpec.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x17\n" +
	"\x15_idle_timeout_minutesB\x1a\n" +
	"\x18_public_ip_prefix_lengthB\xb6\x03\n" +
	"9com.org.project_planton.provider.azure.azurenatgateway.v1B\tSpecProtoP\x01Zwgithub.com/project-planton/project-planton/apis/org/project_planton/provider/azure/azurenatgateway/v1;azurenatgatewayv1\xa2\x02\x05OPPAA\xaa\x024Org.ProjectPlanton.Provider.Azure.Azurenatgateway.V1\xca\x024Org\\ProjectPlanton\\Provider\\Azure\\Azurenatgateway\\V1\xe2\x02@Org\\ProjectPlanton\\Provider\\Azure\\Azurenatgateway\\V1\\GPBMetadata\xea\x029Org::ProjectPlanton::Provider::Azure::Azurenatgateway::V1b\x06proto3"

var (
	file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDescData []byte
)

func file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDesc), len(file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDesc)))
	})
	return file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDescData
}

var file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_goTypes = []any{
	(*AzureNatGatewaySpec)(nil), // 0: org.project_planton.provider.azure.azurenatgateway.v1.AzureNatGatewaySpec
	nil,                         // 1: org.project_planton.provider.azure.azurenatgateway.v1.AzureNatGatewaySpec.TagsEntry
	(*v1.StringValueOrRef)(nil), // 2: org.project_planton.shared.foreignkey.v1.StringValueOrRef
}
var file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_depIdxs = []int32{
	2, // 0: org.project_planton.provider.azure.azurenatgateway.v1.AzureNatGatewaySpec.subnet_id:type_name -> org.project_planton.shared.foreignkey.v1.StringValueOrRef
	1, // 1: org.project_planton.provider.azure.azurenatgateway.v1.AzureNatGatewaySpec.tags:type_name -> org.project_planton.provider.azure.azurenatgateway.v1.AzureNatGatewaySpec.TagsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_init() }
func file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_init() {
	if File_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto != nil {
		return
	}
	file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDesc), len(file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto = out.File
	file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_goTypes = nil
	file_org_project_planton_provider_azure_azurenatgateway_v1_spec_proto_depIdxs = nil
}
