// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: project/planton/provider/gcp/gcpgkenodepool/v1/stack_input.proto

package gcpgkenodepoolv1

import (
	v1 "github.com/project-planton/project-planton/apis/project/planton/credential/gcpcredential/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// input for gcp-gke-node-pool stack
type GcpGkeNodePoolStackInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target cloud-resource
	Target *GcpGkeNodePool `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// provider-credential
	ProviderCredential *v1.GcpCredentialSpec `protobuf:"bytes,2,opt,name=provider_credential,json=providerCredential,proto3" json:"provider_credential,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GcpGkeNodePoolStackInput) Reset() {
	*x = GcpGkeNodePoolStackInput{}
	mi := &file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpGkeNodePoolStackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpGkeNodePoolStackInput) ProtoMessage() {}

func (x *GcpGkeNodePoolStackInput) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpGkeNodePoolStackInput.ProtoReflect.Descriptor instead.
func (*GcpGkeNodePoolStackInput) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDescGZIP(), []int{0}
}

func (x *GcpGkeNodePoolStackInput) GetTarget() *GcpGkeNodePool {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GcpGkeNodePoolStackInput) GetProviderCredential() *v1.GcpCredentialSpec {
	if x != nil {
		return x.ProviderCredential
	}
	return nil
}

var File_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto protoreflect.FileDescriptor

const file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDesc = "" +
	"\n" +
	"@project/planton/provider/gcp/gcpgkenodepool/v1/stack_input.proto\x12.project.planton.provider.gcp.gcpgkenodepool.v1\x1a6project/planton/credential/gcpcredential/v1/spec.proto\x1a8project/planton/provider/gcp/gcpgkenodepool/v1/api.proto\"\xe3\x01\n" +
	"\x18GcpGkeNodePoolStackInput\x12V\n" +
	"\x06target\x18\x01 \x01(\v2>.project.planton.provider.gcp.gcpgkenodepool.v1.GcpGkeNodePoolR\x06target\x12o\n" +
	"\x13provider_credential\x18\x02 \x01(\v2>.project.planton.credential.gcpcredential.v1.GcpCredentialSpecR\x12providerCredentialB\x95\x03\n" +
	"2com.project.planton.provider.gcp.gcpgkenodepool.v1B\x0fStackInputProtoP\x01Zogithub.com/project-planton/project-planton/apis/project/planton/provider/gcp/gcpgkenodepool/v1;gcpgkenodepoolv1\xa2\x02\x05PPPGG\xaa\x02.Project.Planton.Provider.Gcp.Gcpgkenodepool.V1\xca\x02.Project\\Planton\\Provider\\Gcp\\Gcpgkenodepool\\V1\xe2\x02:Project\\Planton\\Provider\\Gcp\\Gcpgkenodepool\\V1\\GPBMetadata\xea\x023Project::Planton::Provider::Gcp::Gcpgkenodepool::V1b\x06proto3"

var (
	file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDescOnce sync.Once
	file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDescData []byte
)

func file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDescGZIP() []byte {
	file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDescOnce.Do(func() {
		file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDesc), len(file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDesc)))
	})
	return file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDescData
}

var file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_goTypes = []any{
	(*GcpGkeNodePoolStackInput)(nil), // 0: project.planton.provider.gcp.gcpgkenodepool.v1.GcpGkeNodePoolStackInput
	(*GcpGkeNodePool)(nil),           // 1: project.planton.provider.gcp.gcpgkenodepool.v1.GcpGkeNodePool
	(*v1.GcpCredentialSpec)(nil),     // 2: project.planton.credential.gcpcredential.v1.GcpCredentialSpec
}
var file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_depIdxs = []int32{
	1, // 0: project.planton.provider.gcp.gcpgkenodepool.v1.GcpGkeNodePoolStackInput.target:type_name -> project.planton.provider.gcp.gcpgkenodepool.v1.GcpGkeNodePool
	2, // 1: project.planton.provider.gcp.gcpgkenodepool.v1.GcpGkeNodePoolStackInput.provider_credential:type_name -> project.planton.credential.gcpcredential.v1.GcpCredentialSpec
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_init() }
func file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_init() {
	if File_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto != nil {
		return
	}
	file_project_planton_provider_gcp_gcpgkenodepool_v1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDesc), len(file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_goTypes,
		DependencyIndexes: file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_depIdxs,
		MessageInfos:      file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_msgTypes,
	}.Build()
	File_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto = out.File
	file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_goTypes = nil
	file_project_planton_provider_gcp_gcpgkenodepool_v1_stack_input_proto_depIdxs = nil
}
