apiVersion: kubernetes.project.planton/v1
kind: MongodbKubernetes
metadata:
  name: test-mongo-database
spec:
  container:
    replicas: 1
    resources:
      limits:
        cpu: 2000m
        memory: 3Gi
      requests:
        cpu: 250m
        memory: 250Mi
    isPersistenceEnabled: true
    diskSize: 8Gi
  ingress:
    isEnabled: true
    dnsDomain: example.com
