apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesHttpEndpoint
metadata:
  name: sub-domain.example.com
spec:
  isTlsEnabled: true
  certClusterIssuerName: Issuer-test
  isGrpcWebCompatible: true
  routingRules:
    - urlPathPrefix: /url-path-prefix-2
      backendService:
        name: servicename-2
        namespace: namespace-2
        port: 8081
