{% if values.create_container_registry | bool %}
---
apiVersion: azure.project-planton.org/v1
kind: AzureContainerRegistry
metadata:
  name: "{{ values.registry_name }}"
spec:
  registryName: "{{ values.registry_name }}"
  sku: "{{ values.registry_sku | upper }}"
  adminUserEnabled: {{ values.registry_admin_enabled }}
  {% endif %}
