{% if values.create_dns_zone | bool %}
---
apiVersion: azure.project-planton.org/v1
kind: AzureDnsZone
metadata:
  name: "{{ values.dns_zone_name }}"
spec:
  zoneName: "{{ values.dns_zone_name }}"
  resourceGroup: "{{ values.dns_resource_group }}"
  {% endif %}
