---
apiVersion: azure.project-planton.org/v1
kind: AzureVpc
metadata:
  name: "{{ values.env }}-vnet"
spec:
  addressSpaceCidr: "{{ values.vnet_cidr }}"
  nodesSubnetCidr: "{{ values.nodes_subnet_cidr }}"
  isNatGatewayEnabled: {{ values.is_nat_gateway_enabled }}
