apiVersion: digital-ocean.project-planton.org/v1
kind: DigitalOceanAppPlatformService
metadata:
  name: first-service                       # Kubernetes object name
spec:
  serviceName: first-service               # must be unique in your DO account
  region: blr1                             # DigitalOceanRegion enum value
  serviceType: web_service                 # web_service | worker | job
  imageSource:
    registry: "docker-hub"         # String or reference to DigitalOceanContainerRegistry
    repository: "nginx"
    tag: "latest"
  instanceSizeSlug: basic_xxs              # basic_xxs | basic_xs | … | professional_xl
  instanceCount: 1                         # default is 1 if omitted
  enableAutoscale: false                   # set true and add min/max to autoscale
  env:
    NODE_ENV: "production"
    APP_VERSION: "v1.0.0"
  # customDomain: "myapp.example.com"      # value or StringValueOrRef to a DigitalOceanDnsZone
