params:
  # ─── Network ───────────────────────────────────────────────────────────────────
  - name: availability_zone_1
    description: First AZ for the public / private subnet pair
    value: us-east-1a

  - name: availability_zone_2
    description: Second AZ for the public / private subnet pair
    value: us-east-1b

  - name: domain_name
    description: Route 53 Hosted‑Zone domain
    value: example.com

  - name: load_balancer_domain_name
    description: DNS name served by the ALB
    value: app.example.com

  # ─── Service basics ────────────────────────────────────────────────────────────
  - name: service_name
    description: ECS service & task family name
    value: nginx

  - name: service_image_repo_name
    description: ECR repository for your service images
    value: shopping-cart-service

  - name: service_port
    description: Container port the task listens on
    value: "80"

  # ─── HTTPS toggle ──────────────────────────────────────────────────────────────
  - name: httpsEnabled                 # NEW
    description: "true → create ACM cert and terminate TLS on the ALB"
    type: bool
    value: true

  # ─── Misc – tweak if required ─────────────────────────────────────────────────
  - name: alb_idle_timeout_seconds
    description: ALB idle timeout
    value: "60"
