apiVersion: kubernetes.project-planton.org/v1
kind: ElasticsearchKubernetes
metadata:
  name: test-elasticsearch-cluster
spec:
  elasticsearch:
    container:
      persistenceEnabled: true
      diskSize: 5Gi
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 50Mi
    ingress:
      enabled: true
      hostname: elasticsearch.example.com
  kibana:
    enabled: true
    container:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 50Mi
    ingress:
      enabled: true
      hostname: kibana.example.com
