export { default as AtlasIcon } from './atlas.svg'
export { default as AwsIcon } from './aws.svg'
export { default as AzureIcon } from './azure.svg'
export { default as ConfluentIcon } from './confluent.svg'
export { default as GcpIcon } from './gcp.svg'
export { default as KubernetesIcon } from './kubernetes.svg'
export { default as SnowflakeIcon } from './snowflake.svg'
