// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "kubernetes:generators.external-secrets.io/v1alpha1:ACRAccessToken":
		r = &ACRAccessToken{}
	case "kubernetes:generators.external-secrets.io/v1alpha1:ECRAuthorizationToken":
		r = &ECRAuthorizationToken{}
	case "kubernetes:generators.external-secrets.io/v1alpha1:Fake":
		r = &Fake{}
	case "kubernetes:generators.external-secrets.io/v1alpha1:GCRAccessToken":
		r = &GCRAccessToken{}
	case "kubernetes:generators.external-secrets.io/v1alpha1:GithubAccessToken":
		r = &GithubAccessToken{}
	case "kubernetes:generators.external-secrets.io/v1alpha1:Password":
		r = &Password{}
	case "kubernetes:generators.external-secrets.io/v1alpha1:VaultDynamicSecret":
		r = &VaultDynamicSecret{}
	case "kubernetes:generators.external-secrets.io/v1alpha1:Webhook":
		r = &Webhook{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := utilities.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"crds",
		"generators.external-secrets.io/v1alpha1",
		&module{version},
	)
}
