// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/kubernetes/kubernetesnamespace/v1/spec.proto

package kubernetesnamespacev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kubernetes "github.com/plantonhq/project-planton/apis/org/project_planton/provider/kubernetes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// **KubernetesNamespacePodSecurityStandard** defines Pod Security Standards enforcement.
// These are Kubernetes-native policies that enforce security best practices.
type KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard int32

const (
	// No enforcement (permissive)
	KubernetesNamespaceSpec_pod_security_standard_unspecified KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard = 0
	// Privileged: Unrestricted policy, allows known privilege escalations.
	// Use only for system-level workloads (monitoring, logging, CNI).
	KubernetesNamespaceSpec_privileged KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard = 1
	// Baseline: Minimally restrictive, prevents known privilege escalations.
	// Suitable for most applications that don't need special permissions.
	KubernetesNamespaceSpec_baseline KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard = 2
	// Restricted: Heavily restricted, follows pod hardening best practices.
	// Use for security-sensitive workloads. May require significant configuration.
	KubernetesNamespaceSpec_restricted KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard = 3
)

// Enum value maps for KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard.
var (
	KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard_name = map[int32]string{
		0: "pod_security_standard_unspecified",
		1: "privileged",
		2: "baseline",
		3: "restricted",
	}
	KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard_value = map[string]int32{
		"pod_security_standard_unspecified": 0,
		"privileged":                        1,
		"baseline":                          2,
		"restricted":                        3,
	}
)

func (x KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard) Enum() *KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard {
	p := new(KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard)
	*p = x
	return p
}

func (x KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard) Descriptor() protoreflect.EnumDescriptor {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes[0].Descriptor()
}

func (KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard) Type() protoreflect.EnumType {
	return &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes[0]
}

func (x KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard.Descriptor instead.
func (KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard) EnumDescriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{0, 0}
}

// *
// **KubernetesNamespaceBuiltInProfile** provides pre-configured resource profiles.
// These implement best practices for CPU, memory, and object count quotas.
type KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile int32

const (
	// Unspecified profile. System will apply a default minimal profile.
	KubernetesNamespaceResourceProfile_built_in_profile_unspecified KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile = 0
	// Small profile for development and testing.
	// CPU: 2 cores request / 4 cores limit
	// Memory: 4Gi request / 8Gi limit
	// Pods: 20, Services: 10, ConfigMaps: 50, Secrets: 50
	KubernetesNamespaceResourceProfile_small KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile = 1
	// Medium profile for staging and small production workloads.
	// CPU: 4 cores request / 8 cores limit
	// Memory: 8Gi request / 16Gi limit
	// Pods: 50, Services: 20, ConfigMaps: 100, Secrets: 100
	KubernetesNamespaceResourceProfile_medium KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile = 2
	// Large profile for production workloads.
	// CPU: 8 cores request / 16 cores limit
	// Memory: 16Gi request / 32Gi limit
	// Pods: 100, Services: 40, ConfigMaps: 200, Secrets: 200
	KubernetesNamespaceResourceProfile_large KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile = 3
	// Extra large profile for high-scale production workloads.
	// CPU: 16 cores request / 32 cores limit
	// Memory: 32Gi request / 64Gi limit
	// Pods: 200, Services: 80, ConfigMaps: 400, Secrets: 400
	KubernetesNamespaceResourceProfile_xlarge KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile = 4
)

// Enum value maps for KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile.
var (
	KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile_name = map[int32]string{
		0: "built_in_profile_unspecified",
		1: "small",
		2: "medium",
		3: "large",
		4: "xlarge",
	}
	KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile_value = map[string]int32{
		"built_in_profile_unspecified": 0,
		"small":                        1,
		"medium":                       2,
		"large":                        3,
		"xlarge":                       4,
	}
)

func (x KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile) Enum() *KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile {
	p := new(KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile)
	*p = x
	return p
}

func (x KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes[1].Descriptor()
}

func (KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile) Type() protoreflect.EnumType {
	return &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes[1]
}

func (x KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile.Descriptor instead.
func (KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile) EnumDescriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{1, 0}
}

// *
// **KubernetesNamespaceServiceMeshType** defines supported service mesh types.
type KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType int32

const (
	// No service mesh
	KubernetesNamespaceServiceMeshConfig_service_mesh_type_unspecified KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType = 0
	// Istio service mesh
	KubernetesNamespaceServiceMeshConfig_istio KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType = 1
	// Linkerd service mesh
	KubernetesNamespaceServiceMeshConfig_linkerd KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType = 2
	// Consul Connect service mesh
	KubernetesNamespaceServiceMeshConfig_consul KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType = 3
)

// Enum value maps for KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType.
var (
	KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType_name = map[int32]string{
		0: "service_mesh_type_unspecified",
		1: "istio",
		2: "linkerd",
		3: "consul",
	}
	KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType_value = map[string]int32{
		"service_mesh_type_unspecified": 0,
		"istio":                         1,
		"linkerd":                       2,
		"consul":                        3,
	}
)

func (x KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType) Enum() *KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType {
	p := new(KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType)
	*p = x
	return p
}

func (x KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType) Descriptor() protoreflect.EnumDescriptor {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes[2].Descriptor()
}

func (KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType) Type() protoreflect.EnumType {
	return &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes[2]
}

func (x KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType.Descriptor instead.
func (KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType) EnumDescriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{8, 0}
}

// *
// **KubernetesNamespaceSpec** defines the configuration for creating and managing a Kubernetes namespace.
// This spec implements a "Namespace-as-a-Service" pattern, abstracting the complexity of namespace
// configuration, resource quotas, network policies, and access control into a batteries-included,
// production-ready primitive.
//
// Based on extensive research into namespace deployment patterns, this spec focuses on the 80/20 rule:
// exposing the 20% of configuration options that deliver 80% of the value while maintaining
// flexibility for advanced use cases.
type KubernetesNamespaceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Kubernetes cluster in which the namespace should be created
	TargetCluster *kubernetes.KubernetesClusterSelector `protobuf:"bytes,1,opt,name=target_cluster,json=targetCluster,proto3" json:"target_cluster,omitempty"`
	// *
	// The unique name of the namespace.
	// This will be used as the Kubernetes namespace metadata.name.
	// Must be a valid DNS label (lowercase alphanumeric and hyphens).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// Additional labels to be applied to the namespace.
	// These are merged with standard labels (environment, team, cost-center) for
	// cost allocation, monitoring, and governance.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// *
	// Additional annotations to be applied to the namespace.
	// Common use cases:
	// - linkerd.io/inject: "enabled" for service mesh injection
	// - janitor/ttl: "24h" for ephemeral namespace cleanup
	// - scheduler.alpha.kubernetes.io/node-selector: for node affinity
	Annotations map[string]string `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// *
	// Resource allocation profile for the namespace.
	// This abstracts ResourceQuota and LimitRange configuration into T-shirt sizes
	// or allows custom specifications for advanced users.
	ResourceProfile *KubernetesNamespaceResourceProfile `protobuf:"bytes,5,opt,name=resource_profile,json=resourceProfile,proto3" json:"resource_profile,omitempty"`
	// *
	// Network isolation and security configuration.
	// Controls ingress/egress network policies to enforce zero-trust networking.
	NetworkConfig *KubernetesNamespaceNetworkConfig `protobuf:"bytes,6,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`
	// *
	// Service mesh integration configuration.
	// Enables automatic sidecar injection and mesh-specific features.
	ServiceMeshConfig *KubernetesNamespaceServiceMeshConfig `protobuf:"bytes,7,opt,name=service_mesh_config,json=serviceMeshConfig,proto3" json:"service_mesh_config,omitempty"`
	// *
	// Pod security standards enforcement level.
	// Defines the security posture for pods running in the namespace.
	PodSecurityStandard KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard `protobuf:"varint,8,opt,name=pod_security_standard,json=podSecurityStandard,proto3,enum=org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard" json:"pod_security_standard,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *KubernetesNamespaceSpec) Reset() {
	*x = KubernetesNamespaceSpec{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceSpec) ProtoMessage() {}

func (x *KubernetesNamespaceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceSpec.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceSpec) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesNamespaceSpec) GetTargetCluster() *kubernetes.KubernetesClusterSelector {
	if x != nil {
		return x.TargetCluster
	}
	return nil
}

func (x *KubernetesNamespaceSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubernetesNamespaceSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *KubernetesNamespaceSpec) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *KubernetesNamespaceSpec) GetResourceProfile() *KubernetesNamespaceResourceProfile {
	if x != nil {
		return x.ResourceProfile
	}
	return nil
}

func (x *KubernetesNamespaceSpec) GetNetworkConfig() *KubernetesNamespaceNetworkConfig {
	if x != nil {
		return x.NetworkConfig
	}
	return nil
}

func (x *KubernetesNamespaceSpec) GetServiceMeshConfig() *KubernetesNamespaceServiceMeshConfig {
	if x != nil {
		return x.ServiceMeshConfig
	}
	return nil
}

func (x *KubernetesNamespaceSpec) GetPodSecurityStandard() KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard {
	if x != nil {
		return x.PodSecurityStandard
	}
	return KubernetesNamespaceSpec_pod_security_standard_unspecified
}

// *
// **KubernetesNamespaceResourceProfile** defines resource limits and quotas for the namespace.
// This abstracts the complexity of ResourceQuota and LimitRange into intuitive profiles.
type KubernetesNamespaceResourceProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ProfileConfig:
	//
	//	*KubernetesNamespaceResourceProfile_Preset
	//	*KubernetesNamespaceResourceProfile_Custom
	ProfileConfig isKubernetesNamespaceResourceProfile_ProfileConfig `protobuf_oneof:"profile_config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesNamespaceResourceProfile) Reset() {
	*x = KubernetesNamespaceResourceProfile{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceResourceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceResourceProfile) ProtoMessage() {}

func (x *KubernetesNamespaceResourceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceResourceProfile.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceResourceProfile) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesNamespaceResourceProfile) GetProfileConfig() isKubernetesNamespaceResourceProfile_ProfileConfig {
	if x != nil {
		return x.ProfileConfig
	}
	return nil
}

func (x *KubernetesNamespaceResourceProfile) GetPreset() KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile {
	if x != nil {
		if x, ok := x.ProfileConfig.(*KubernetesNamespaceResourceProfile_Preset); ok {
			return x.Preset
		}
	}
	return KubernetesNamespaceResourceProfile_built_in_profile_unspecified
}

func (x *KubernetesNamespaceResourceProfile) GetCustom() *KubernetesNamespaceCustomQuotas {
	if x != nil {
		if x, ok := x.ProfileConfig.(*KubernetesNamespaceResourceProfile_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isKubernetesNamespaceResourceProfile_ProfileConfig interface {
	isKubernetesNamespaceResourceProfile_ProfileConfig()
}

type KubernetesNamespaceResourceProfile_Preset struct {
	// Pre-defined T-shirt size profiles (small, medium, large, xlarge).
	// These provide opinionated defaults for different namespace sizes.
	Preset KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile `protobuf:"varint,1,opt,name=preset,proto3,enum=org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile,oneof"`
}

type KubernetesNamespaceResourceProfile_Custom struct {
	// Custom resource limits for advanced users who need precise control.
	Custom *KubernetesNamespaceCustomQuotas `protobuf:"bytes,2,opt,name=custom,proto3,oneof"`
}

func (*KubernetesNamespaceResourceProfile_Preset) isKubernetesNamespaceResourceProfile_ProfileConfig() {
}

func (*KubernetesNamespaceResourceProfile_Custom) isKubernetesNamespaceResourceProfile_ProfileConfig() {
}

// *
// **KubernetesNamespaceCustomQuotas** allows explicit specification of resource limits.
// This is for advanced users who need precise control over quotas.
type KubernetesNamespaceCustomQuotas struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU resource limits
	Cpu *KubernetesNamespaceCpuQuota `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Memory resource limits
	Memory *KubernetesNamespaceMemoryQuota `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	// Object count limits (pods, services, configmaps, secrets)
	ObjectCounts *KubernetesNamespaceObjectCountQuotas `protobuf:"bytes,3,opt,name=object_counts,json=objectCounts,proto3" json:"object_counts,omitempty"`
	// Default resource requests/limits for containers without explicit values
	DefaultLimits *KubernetesNamespaceDefaultLimits `protobuf:"bytes,4,opt,name=default_limits,json=defaultLimits,proto3" json:"default_limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesNamespaceCustomQuotas) Reset() {
	*x = KubernetesNamespaceCustomQuotas{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceCustomQuotas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceCustomQuotas) ProtoMessage() {}

func (x *KubernetesNamespaceCustomQuotas) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceCustomQuotas.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceCustomQuotas) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesNamespaceCustomQuotas) GetCpu() *KubernetesNamespaceCpuQuota {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *KubernetesNamespaceCustomQuotas) GetMemory() *KubernetesNamespaceMemoryQuota {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *KubernetesNamespaceCustomQuotas) GetObjectCounts() *KubernetesNamespaceObjectCountQuotas {
	if x != nil {
		return x.ObjectCounts
	}
	return nil
}

func (x *KubernetesNamespaceCustomQuotas) GetDefaultLimits() *KubernetesNamespaceDefaultLimits {
	if x != nil {
		return x.DefaultLimits
	}
	return nil
}

// *
// **KubernetesNamespaceCpuQuota** defines CPU resource quotas.
type KubernetesNamespaceCpuQuota struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total CPU requests allowed (e.g., "4", "4000m")
	Requests string `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	// Total CPU limits allowed (e.g., "8", "8000m")
	Limits        string `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesNamespaceCpuQuota) Reset() {
	*x = KubernetesNamespaceCpuQuota{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceCpuQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceCpuQuota) ProtoMessage() {}

func (x *KubernetesNamespaceCpuQuota) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceCpuQuota.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceCpuQuota) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *KubernetesNamespaceCpuQuota) GetRequests() string {
	if x != nil {
		return x.Requests
	}
	return ""
}

func (x *KubernetesNamespaceCpuQuota) GetLimits() string {
	if x != nil {
		return x.Limits
	}
	return ""
}

// *
// **KubernetesNamespaceMemoryQuota** defines memory resource quotas.
type KubernetesNamespaceMemoryQuota struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total memory requests allowed (e.g., "8Gi", "8192Mi")
	Requests string `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	// Total memory limits allowed (e.g., "16Gi", "16384Mi")
	Limits        string `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesNamespaceMemoryQuota) Reset() {
	*x = KubernetesNamespaceMemoryQuota{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceMemoryQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceMemoryQuota) ProtoMessage() {}

func (x *KubernetesNamespaceMemoryQuota) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceMemoryQuota.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceMemoryQuota) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{4}
}

func (x *KubernetesNamespaceMemoryQuota) GetRequests() string {
	if x != nil {
		return x.Requests
	}
	return ""
}

func (x *KubernetesNamespaceMemoryQuota) GetLimits() string {
	if x != nil {
		return x.Limits
	}
	return ""
}

// *
// **KubernetesNamespaceObjectCountQuotas** defines limits on Kubernetes object counts.
// This prevents control plane exhaustion from excessive object creation.
type KubernetesNamespaceObjectCountQuotas struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of pods
	Pods int32 `protobuf:"varint,1,opt,name=pods,proto3" json:"pods,omitempty"`
	// Maximum number of services
	Services int32 `protobuf:"varint,2,opt,name=services,proto3" json:"services,omitempty"`
	// Maximum number of configmaps
	Configmaps int32 `protobuf:"varint,3,opt,name=configmaps,proto3" json:"configmaps,omitempty"`
	// Maximum number of secrets
	Secrets int32 `protobuf:"varint,4,opt,name=secrets,proto3" json:"secrets,omitempty"`
	// Maximum number of persistent volume claims
	PersistentVolumeClaims int32 `protobuf:"varint,5,opt,name=persistent_volume_claims,json=persistentVolumeClaims,proto3" json:"persistent_volume_claims,omitempty"`
	// Maximum number of load balancers
	LoadBalancers int32 `protobuf:"varint,6,opt,name=load_balancers,json=loadBalancers,proto3" json:"load_balancers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesNamespaceObjectCountQuotas) Reset() {
	*x = KubernetesNamespaceObjectCountQuotas{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceObjectCountQuotas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceObjectCountQuotas) ProtoMessage() {}

func (x *KubernetesNamespaceObjectCountQuotas) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceObjectCountQuotas.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceObjectCountQuotas) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{5}
}

func (x *KubernetesNamespaceObjectCountQuotas) GetPods() int32 {
	if x != nil {
		return x.Pods
	}
	return 0
}

func (x *KubernetesNamespaceObjectCountQuotas) GetServices() int32 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *KubernetesNamespaceObjectCountQuotas) GetConfigmaps() int32 {
	if x != nil {
		return x.Configmaps
	}
	return 0
}

func (x *KubernetesNamespaceObjectCountQuotas) GetSecrets() int32 {
	if x != nil {
		return x.Secrets
	}
	return 0
}

func (x *KubernetesNamespaceObjectCountQuotas) GetPersistentVolumeClaims() int32 {
	if x != nil {
		return x.PersistentVolumeClaims
	}
	return 0
}

func (x *KubernetesNamespaceObjectCountQuotas) GetLoadBalancers() int32 {
	if x != nil {
		return x.LoadBalancers
	}
	return 0
}

// *
// **KubernetesNamespaceDefaultLimits** defines default resource requests/limits.
// These are automatically injected into containers that don't specify their own values.
// This is implemented via LimitRange in Kubernetes.
type KubernetesNamespaceDefaultLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default CPU request (e.g., "100m")
	DefaultCpuRequest string `protobuf:"bytes,1,opt,name=default_cpu_request,json=defaultCpuRequest,proto3" json:"default_cpu_request,omitempty"`
	// Default CPU limit (e.g., "1000m")
	DefaultCpuLimit string `protobuf:"bytes,2,opt,name=default_cpu_limit,json=defaultCpuLimit,proto3" json:"default_cpu_limit,omitempty"`
	// Default memory request (e.g., "128Mi")
	DefaultMemoryRequest string `protobuf:"bytes,3,opt,name=default_memory_request,json=defaultMemoryRequest,proto3" json:"default_memory_request,omitempty"`
	// Default memory limit (e.g., "512Mi")
	DefaultMemoryLimit string `protobuf:"bytes,4,opt,name=default_memory_limit,json=defaultMemoryLimit,proto3" json:"default_memory_limit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KubernetesNamespaceDefaultLimits) Reset() {
	*x = KubernetesNamespaceDefaultLimits{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceDefaultLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceDefaultLimits) ProtoMessage() {}

func (x *KubernetesNamespaceDefaultLimits) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceDefaultLimits.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceDefaultLimits) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{6}
}

func (x *KubernetesNamespaceDefaultLimits) GetDefaultCpuRequest() string {
	if x != nil {
		return x.DefaultCpuRequest
	}
	return ""
}

func (x *KubernetesNamespaceDefaultLimits) GetDefaultCpuLimit() string {
	if x != nil {
		return x.DefaultCpuLimit
	}
	return ""
}

func (x *KubernetesNamespaceDefaultLimits) GetDefaultMemoryRequest() string {
	if x != nil {
		return x.DefaultMemoryRequest
	}
	return ""
}

func (x *KubernetesNamespaceDefaultLimits) GetDefaultMemoryLimit() string {
	if x != nil {
		return x.DefaultMemoryLimit
	}
	return ""
}

// *
// **KubernetesNamespaceNetworkConfig** defines network isolation and security policies.
// This implements the "Default Deny" security pattern with explicit allow rules.
type KubernetesNamespaceNetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Enable ingress network isolation.
	// When true, creates a NetworkPolicy that denies all ingress traffic by default.
	// Traffic must be explicitly allowed.
	IsolateIngress bool `protobuf:"varint,1,opt,name=isolate_ingress,json=isolateIngress,proto3" json:"isolate_ingress,omitempty"`
	// *
	// Enable egress network restriction.
	// When true, blocks all egress except to kube-system (DNS) and Kubernetes API.
	// This prevents pods from accessing external networks without explicit rules.
	RestrictEgress bool `protobuf:"varint,2,opt,name=restrict_egress,json=restrictEgress,proto3" json:"restrict_egress,omitempty"`
	// *
	// Allow ingress from specific namespaces.
	// List of namespace names that are allowed to send traffic to this namespace.
	AllowedIngressNamespaces []string `protobuf:"bytes,3,rep,name=allowed_ingress_namespaces,json=allowedIngressNamespaces,proto3" json:"allowed_ingress_namespaces,omitempty"`
	// *
	// Allow egress to specific external CIDR blocks.
	// List of CIDR blocks (e.g., "10.0.0.0/8", "192.168.1.0/24") that pods can access.
	AllowedEgressCidrs []string `protobuf:"bytes,4,rep,name=allowed_egress_cidrs,json=allowedEgressCidrs,proto3" json:"allowed_egress_cidrs,omitempty"`
	// *
	// Allow egress to specific DNS domains.
	// List of domains (e.g., "api.stripe.com", "*.github.com") that pods can access.
	// Requires a CNI that supports DNS-based policies (like Calico or Cilium).
	AllowedEgressDomains []string `protobuf:"bytes,5,rep,name=allowed_egress_domains,json=allowedEgressDomains,proto3" json:"allowed_egress_domains,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *KubernetesNamespaceNetworkConfig) Reset() {
	*x = KubernetesNamespaceNetworkConfig{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceNetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceNetworkConfig) ProtoMessage() {}

func (x *KubernetesNamespaceNetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceNetworkConfig.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceNetworkConfig) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{7}
}

func (x *KubernetesNamespaceNetworkConfig) GetIsolateIngress() bool {
	if x != nil {
		return x.IsolateIngress
	}
	return false
}

func (x *KubernetesNamespaceNetworkConfig) GetRestrictEgress() bool {
	if x != nil {
		return x.RestrictEgress
	}
	return false
}

func (x *KubernetesNamespaceNetworkConfig) GetAllowedIngressNamespaces() []string {
	if x != nil {
		return x.AllowedIngressNamespaces
	}
	return nil
}

func (x *KubernetesNamespaceNetworkConfig) GetAllowedEgressCidrs() []string {
	if x != nil {
		return x.AllowedEgressCidrs
	}
	return nil
}

func (x *KubernetesNamespaceNetworkConfig) GetAllowedEgressDomains() []string {
	if x != nil {
		return x.AllowedEgressDomains
	}
	return nil
}

// *
// **KubernetesNamespaceServiceMeshConfig** defines service mesh integration.
// This supports automatic sidecar injection and mesh lifecycle management.
type KubernetesNamespaceServiceMeshConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Enable service mesh sidecar injection.
	// When true, service mesh proxies are automatically injected into pods.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// *
	// Service mesh type.
	// Determines which mesh to use (Istio, Linkerd, etc.).
	MeshType KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType `protobuf:"varint,2,opt,name=mesh_type,json=meshType,proto3,enum=org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType" json:"mesh_type,omitempty"`
	// *
	// Mesh revision tag (Istio-specific).
	// Allows pointing to a specific control plane version without hardcoding the version.
	// Example: "prod-stable", "canary", "1-19-5"
	// This enables safe, granular mesh upgrades.
	RevisionTag   string `protobuf:"bytes,3,opt,name=revision_tag,json=revisionTag,proto3" json:"revision_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesNamespaceServiceMeshConfig) Reset() {
	*x = KubernetesNamespaceServiceMeshConfig{}
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesNamespaceServiceMeshConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesNamespaceServiceMeshConfig) ProtoMessage() {}

func (x *KubernetesNamespaceServiceMeshConfig) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesNamespaceServiceMeshConfig.ProtoReflect.Descriptor instead.
func (*KubernetesNamespaceServiceMeshConfig) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP(), []int{8}
}

func (x *KubernetesNamespaceServiceMeshConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *KubernetesNamespaceServiceMeshConfig) GetMeshType() KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType {
	if x != nil {
		return x.MeshType
	}
	return KubernetesNamespaceServiceMeshConfig_service_mesh_type_unspecified
}

func (x *KubernetesNamespaceServiceMeshConfig) GetRevisionTag() string {
	if x != nil {
		return x.RevisionTag
	}
	return ""
}

var File_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDesc = "" +
	"\n" +
	"Iorg/project_planton/provider/kubernetes/kubernetesnamespace/v1/spec.proto\x12>org.project_planton.provider.kubernetes.kubernetesnamespace.v1\x1a\x1bbuf/validate/validate.proto\x1a<org/project_planton/provider/kubernetes/target_cluster.proto\"\xf3\f\n" +
	"\x17KubernetesNamespaceSpec\x12i\n" +
	"\x0etarget_cluster\x18\x01 \x01(\v2B.org.project_planton.provider.kubernetes.KubernetesClusterSelectorR\rtargetCluster\x12\xcb\x01\n" +
	"\x04name\x18\x02 \x01(\tB\xb6\x01\xbaH\xb2\x01\xba\x01\xa8\x01\n" +
	"\x0ename.dns_label\x12`Name must be a valid DNS label (lowercase alphanumeric and hyphens, no leading/trailing hyphens)\x1a4this.matches('^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$')r\x04\x10\x01\x18?R\x04name\x12{\n" +
	"\x06labels\x18\x03 \x03(\v2c.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.LabelsEntryR\x06labels\x12\x8a\x01\n" +
	"\vannotations\x18\x04 \x03(\v2h.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.AnnotationsEntryR\vannotations\x12\x8d\x01\n" +
	"\x10resource_profile\x18\x05 \x01(\v2b.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfileR\x0fresourceProfile\x12\x87\x01\n" +
	"\x0enetwork_config\x18\x06 \x01(\v2`.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceNetworkConfigR\rnetworkConfig\x12\x94\x01\n" +
	"\x13service_mesh_config\x18\a \x01(\v2d.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfigR\x11serviceMeshConfig\x12\xbc\x01\n" +
	"\x15pod_security_standard\x18\b \x01(\x0e2~.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.KubernetesNamespacePodSecurityStandardB\b\xbaH\x05\x82\x01\x02\x10\x01R\x13podSecurityStandard\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"&KubernetesNamespacePodSecurityStandard\x12%\n" +
	"!pod_security_standard_unspecified\x10\x00\x12\x0e\n" +
	"\n" +
	"privileged\x10\x01\x12\f\n" +
	"\bbaseline\x10\x02\x12\x0e\n" +
	"\n" +
	"restricted\x10\x03:\xaa\x01\xbaH\xa6\x01\x1a\xa3\x01\n" +
	"\x1fservice_mesh_requires_mesh_type\x122mesh_type must be set when service mesh is enabled\x1aL!this.service_mesh_config.enabled || this.service_mesh_config.mesh_type != 0\"\xd2\x03\n" +
	"\"KubernetesNamespaceResourceProfile\x12\xa9\x01\n" +
	"\x06preset\x18\x01 \x01(\x0e2\x84\x01.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile.KubernetesNamespaceBuiltInProfileB\b\xbaH\x05\x82\x01\x02\x10\x01H\x00R\x06preset\x12y\n" +
	"\x06custom\x18\x02 \x01(\v2_.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCustomQuotasH\x00R\x06custom\"s\n" +
	"!KubernetesNamespaceBuiltInProfile\x12 \n" +
	"\x1cbuilt_in_profile_unspecified\x10\x00\x12\t\n" +
	"\x05small\x10\x01\x12\n" +
	"\n" +
	"\x06medium\x10\x02\x12\t\n" +
	"\x05large\x10\x03\x12\n" +
	"\n" +
	"\x06xlarge\x10\x04B\x10\n" +
	"\x0eprofile_config\"\x9e\x04\n" +
	"\x1fKubernetesNamespaceCustomQuotas\x12m\n" +
	"\x03cpu\x18\x01 \x01(\v2[.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCpuQuotaR\x03cpu\x12v\n" +
	"\x06memory\x18\x02 \x01(\v2^.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceMemoryQuotaR\x06memory\x12\x89\x01\n" +
	"\robject_counts\x18\x03 \x01(\v2d.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceObjectCountQuotasR\fobjectCounts\x12\x87\x01\n" +
	"\x0edefault_limits\x18\x04 \x01(\v2`.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceDefaultLimitsR\rdefaultLimits\"c\n" +
	"\x1bKubernetesNamespaceCpuQuota\x12#\n" +
	"\brequests\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brequests\x12\x1f\n" +
	"\x06limits\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06limits\"f\n" +
	"\x1eKubernetesNamespaceMemoryQuota\x12#\n" +
	"\brequests\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\brequests\x12\x1f\n" +
	"\x06limits\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06limits\"\xa7\x02\n" +
	"$KubernetesNamespaceObjectCountQuotas\x12\x1b\n" +
	"\x04pods\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x04pods\x12#\n" +
	"\bservices\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\bservices\x12'\n" +
	"\n" +
	"configmaps\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\n" +
	"configmaps\x12!\n" +
	"\asecrets\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\asecrets\x12A\n" +
	"\x18persistent_volume_claims\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x16persistentVolumeClaims\x12.\n" +
	"\x0eload_balancers\x18\x06 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\rloadBalancers\"\x8a\x02\n" +
	" KubernetesNamespaceDefaultLimits\x127\n" +
	"\x13default_cpu_request\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x11defaultCpuRequest\x123\n" +
	"\x11default_cpu_limit\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fdefaultCpuLimit\x12=\n" +
	"\x16default_memory_request\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x14defaultMemoryRequest\x129\n" +
	"\x14default_memory_limit\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x12defaultMemoryLimit\"\x9a\x02\n" +
	" KubernetesNamespaceNetworkConfig\x12'\n" +
	"\x0fisolate_ingress\x18\x01 \x01(\bR\x0eisolateIngress\x12'\n" +
	"\x0frestrict_egress\x18\x02 \x01(\bR\x0erestrictEgress\x12<\n" +
	"\x1aallowed_ingress_namespaces\x18\x03 \x03(\tR\x18allowedIngressNamespaces\x120\n" +
	"\x14allowed_egress_cidrs\x18\x04 \x03(\tR\x12allowedEgressCidrs\x124\n" +
	"\x16allowed_egress_domains\x18\x05 \x03(\tR\x14allowedEgressDomains\"\x8b\x03\n" +
	"$KubernetesNamespaceServiceMeshConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\xaf\x01\n" +
	"\tmesh_type\x18\x02 \x01(\x0e2\x87\x01.org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfig.KubernetesNamespaceServiceMeshTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\bmeshType\x12*\n" +
	"\frevision_tag\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x18?R\vrevisionTag\"k\n" +
	"\"KubernetesNamespaceServiceMeshType\x12!\n" +
	"\x1dservice_mesh_type_unspecified\x10\x00\x12\t\n" +
	"\x05istio\x10\x01\x12\v\n" +
	"\alinkerd\x10\x02\x12\n" +
	"\n" +
	"\x06consul\x10\x03B\xea\x03\n" +
	"Bcom.org.project_planton.provider.kubernetes.kubernetesnamespace.v1B\tSpecProtoP\x01Z~github.com/plantonhq/project-planton/apis/org/project_planton/provider/kubernetes/kubernetesnamespace/v1;kubernetesnamespacev1\xa2\x02\x05OPPKK\xaa\x02=Org.ProjectPlanton.Provider.Kubernetes.Kubernetesnamespace.V1\xca\x02=Org\\ProjectPlanton\\Provider\\Kubernetes\\Kubernetesnamespace\\V1\xe2\x02IOrg\\ProjectPlanton\\Provider\\Kubernetes\\Kubernetesnamespace\\V1\\GPBMetadata\xea\x02BOrg::ProjectPlanton::Provider::Kubernetes::Kubernetesnamespace::V1b\x06proto3"

var (
	file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescData []byte
)

func file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDesc), len(file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDesc)))
	})
	return file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDescData
}

var file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_goTypes = []any{
	(KubernetesNamespaceSpec_KubernetesNamespacePodSecurityStandard)(0),          // 0: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.KubernetesNamespacePodSecurityStandard
	(KubernetesNamespaceResourceProfile_KubernetesNamespaceBuiltInProfile)(0),    // 1: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile.KubernetesNamespaceBuiltInProfile
	(KubernetesNamespaceServiceMeshConfig_KubernetesNamespaceServiceMeshType)(0), // 2: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfig.KubernetesNamespaceServiceMeshType
	(*KubernetesNamespaceSpec)(nil),                                              // 3: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec
	(*KubernetesNamespaceResourceProfile)(nil),                                   // 4: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile
	(*KubernetesNamespaceCustomQuotas)(nil),                                      // 5: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCustomQuotas
	(*KubernetesNamespaceCpuQuota)(nil),                                          // 6: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCpuQuota
	(*KubernetesNamespaceMemoryQuota)(nil),                                       // 7: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceMemoryQuota
	(*KubernetesNamespaceObjectCountQuotas)(nil),                                 // 8: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceObjectCountQuotas
	(*KubernetesNamespaceDefaultLimits)(nil),                                     // 9: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceDefaultLimits
	(*KubernetesNamespaceNetworkConfig)(nil),                                     // 10: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceNetworkConfig
	(*KubernetesNamespaceServiceMeshConfig)(nil),                                 // 11: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfig
	nil, // 12: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.LabelsEntry
	nil, // 13: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.AnnotationsEntry
	(*kubernetes.KubernetesClusterSelector)(nil), // 14: org.project_planton.provider.kubernetes.KubernetesClusterSelector
}
var file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_depIdxs = []int32{
	14, // 0: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.target_cluster:type_name -> org.project_planton.provider.kubernetes.KubernetesClusterSelector
	12, // 1: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.labels:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.LabelsEntry
	13, // 2: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.annotations:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.AnnotationsEntry
	4,  // 3: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.resource_profile:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile
	10, // 4: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.network_config:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceNetworkConfig
	11, // 5: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.service_mesh_config:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfig
	0,  // 6: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.pod_security_standard:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceSpec.KubernetesNamespacePodSecurityStandard
	1,  // 7: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile.preset:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile.KubernetesNamespaceBuiltInProfile
	5,  // 8: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceResourceProfile.custom:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCustomQuotas
	6,  // 9: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCustomQuotas.cpu:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCpuQuota
	7,  // 10: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCustomQuotas.memory:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceMemoryQuota
	8,  // 11: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCustomQuotas.object_counts:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceObjectCountQuotas
	9,  // 12: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceCustomQuotas.default_limits:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceDefaultLimits
	2,  // 13: org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfig.mesh_type:type_name -> org.project_planton.provider.kubernetes.kubernetesnamespace.v1.KubernetesNamespaceServiceMeshConfig.KubernetesNamespaceServiceMeshType
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_init() }
func file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_init() {
	if File_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto != nil {
		return
	}
	file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes[1].OneofWrappers = []any{
		(*KubernetesNamespaceResourceProfile_Preset)(nil),
		(*KubernetesNamespaceResourceProfile_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDesc), len(file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_depIdxs,
		EnumInfos:         file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_enumTypes,
		MessageInfos:      file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto = out.File
	file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_goTypes = nil
	file_org_project_planton_provider_kubernetes_kubernetesnamespace_v1_spec_proto_depIdxs = nil
}
