apiVersion: azure.project-planton.org/v1
kind: AzureAksCluster
metadata:
  name: production-aks-cluster
  labels:
    environment: production
    team: platform
spec:
  # Required: Azure region
  region: eastus
  
  # Required: VNet subnet ID for AKS nodes
  # Replace with your actual subnet ID
  vnetSubnetId:
    value: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-network/providers/Microsoft.Network/virtualNetworks/my-vnet/subnets/aks-nodes-subnet
  
  # Kubernetes version - pin to specific version to prevent unintended upgrades
  kubernetesVersion: "1.30"
  
  # Control plane SKU - STANDARD provides financially-backed 99.95% uptime SLA
  # Use FREE only for dev/test environments
  controlPlaneSku: STANDARD
  
  # Network configuration
  networkPlugin: AZURE_CNI
  networkPluginMode: OVERLAY  # Modern, IP-efficient networking that solves VNet IP exhaustion
  
  # API server access configuration
  privateClusterEnabled: false
  authorizedIpRanges:
    - "203.0.113.0/24"  # Office network CIDR
    - "198.51.100.0/24"  # CI/CD agents network
  
  # Azure AD RBAC integration (enabled by default for production)
  disableAzureAdRbac: false
  
  # Required: System node pool configuration
  # System pools run critical AKS components (CoreDNS, metrics-server, etc.)
  systemNodePool:
    vmSize: Standard_D4s_v5  # 4 vCPU, 16 GB RAM - recommended for production
    autoscaling:
      minCount: 3  # Minimum 3 nodes for high availability
      maxCount: 5
    availabilityZones:
      - "1"
      - "2"
      - "3"  # Deploy across 3 AZs for 99.95% SLA
  
  # User node pools for application workloads
  userNodePools:
    - name: general
      vmSize: Standard_D8s_v5  # 8 vCPU, 32 GB RAM
      autoscaling:
        minCount: 2
        maxCount: 10
      availabilityZones:
        - "1"
        - "2"
        - "3"
      spotEnabled: false
    
    # Optional: Spot instance pool for fault-tolerant workloads
    - name: spot
      vmSize: Standard_D4s_v5
      autoscaling:
        minCount: 0
        maxCount: 20
      availabilityZones:
        - "1"
        - "2"
        - "3"
      spotEnabled: true  # 30-90% cost savings, but can be evicted
  
  # Add-ons configuration
  addons:
    # Container Insights streams logs and metrics to Log Analytics
    enableContainerInsights: true
    logAnalyticsWorkspaceId: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-monitoring/providers/Microsoft.OperationalInsights/workspaces/aks-logs
    
    # Key Vault CSI driver allows pods to mount secrets from Azure Key Vault
    enableKeyVaultCsiDriver: true
    
    # Azure Policy enforces governance policies on the cluster
    enableAzurePolicy: true
    
    # Workload Identity enables secret-less authentication for pods to Azure services
    enableWorkloadIdentity: true
  
  # Advanced networking configuration (optional)
  # Most users should rely on defaults - only customize if needed
  advancedNetworking:
    podCidr: "10.244.0.0/16"      # Pod CIDR for Overlay mode
    serviceCidr: "10.0.0.0/16"    # Service CIDR for Kubernetes services
    dnsServiceIp: "10.0.0.10"     # DNS service IP (must be within serviceCidr)

