// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/gcp/gcpartifactregistryrepo/v1/api.proto

package gcpartifactregistryrepov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/project-planton/apis/org/project_planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gcp-artifact-registry-repo
type GcpArtifactRegistryRepo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// resource spec
	Spec *GcpArtifactRegistryRepoSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// resource status
	Status        *GcpArtifactRegistryRepoStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpArtifactRegistryRepo) Reset() {
	*x = GcpArtifactRegistryRepo{}
	mi := &file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpArtifactRegistryRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpArtifactRegistryRepo) ProtoMessage() {}

func (x *GcpArtifactRegistryRepo) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpArtifactRegistryRepo.ProtoReflect.Descriptor instead.
func (*GcpArtifactRegistryRepo) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GcpArtifactRegistryRepo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GcpArtifactRegistryRepo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GcpArtifactRegistryRepo) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GcpArtifactRegistryRepo) GetSpec() *GcpArtifactRegistryRepoSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *GcpArtifactRegistryRepo) GetStatus() *GcpArtifactRegistryRepoStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// gcp-artifact-registry-repo status
type GcpArtifactRegistryRepoStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs for gcp-artifact-registry-repo
	Outputs       *GcpArtifactRegistryRepoStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpArtifactRegistryRepoStatus) Reset() {
	*x = GcpArtifactRegistryRepoStatus{}
	mi := &file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpArtifactRegistryRepoStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpArtifactRegistryRepoStatus) ProtoMessage() {}

func (x *GcpArtifactRegistryRepoStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpArtifactRegistryRepoStatus.ProtoReflect.Descriptor instead.
func (*GcpArtifactRegistryRepoStatus) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GcpArtifactRegistryRepoStatus) GetOutputs() *GcpArtifactRegistryRepoStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDesc = "" +
	"\n" +
	"Eorg/project_planton/provider/gcp/gcpartifactregistryrepo/v1/api.proto\x12;org.project_planton.provider.gcp.gcpartifactregistryrepo.v1\x1a\x1bbuf/validate/validate.proto\x1aForg/project_planton/provider/gcp/gcpartifactregistryrepo/v1/spec.proto\x1aOorg/project_planton/provider/gcp/gcpartifactregistryrepo/v1/stack_outputs.proto\x1a)org/project_planton/shared/metadata.proto\"\xd2\x03\n" +
	"\x17GcpArtifactRegistryRepo\x12B\n" +
	"\vapi_version\x18\x01 \x01(\tB!\xbaH\x1er\x1c\n" +
	"\x1agcp.project-planton.org/v1R\n" +
	"apiVersion\x122\n" +
	"\x04kind\x18\x02 \x01(\tB\x1e\xbaH\x1br\x19\n" +
	"\x17GcpArtifactRegistryRepoR\x04kind\x12U\n" +
	"\bmetadata\x18\x03 \x01(\v21.org.project_planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12t\n" +
	"\x04spec\x18\x04 \x01(\v2X.org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12r\n" +
	"\x06status\x18\x05 \x01(\v2Z.org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoStatusR\x06status\"\x9b\x01\n" +
	"\x1dGcpArtifactRegistryRepoStatus\x12z\n" +
	"\aoutputs\x18\x01 \x01(\v2`.org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoStackOutputsR\aoutputsB\xdb\x03\n" +
	"?com.org.project_planton.provider.gcp.gcpartifactregistryrepo.v1B\bApiProtoP\x01Z\x7fgithub.com/plantonhq/project-planton/apis/org/project_planton/provider/gcp/gcpartifactregistryrepo/v1;gcpartifactregistryrepov1\xa2\x02\x05OPPGG\xaa\x02:Org.ProjectPlanton.Provider.Gcp.Gcpartifactregistryrepo.V1\xca\x02:Org\\ProjectPlanton\\Provider\\Gcp\\Gcpartifactregistryrepo\\V1\xe2\x02FOrg\\ProjectPlanton\\Provider\\Gcp\\Gcpartifactregistryrepo\\V1\\GPBMetadata\xea\x02?Org::ProjectPlanton::Provider::Gcp::Gcpartifactregistryrepo::V1b\x06proto3"

var (
	file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescData []byte
)

func file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDesc), len(file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDesc)))
	})
	return file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDescData
}

var file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_goTypes = []any{
	(*GcpArtifactRegistryRepo)(nil),             // 0: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepo
	(*GcpArtifactRegistryRepoStatus)(nil),       // 1: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoStatus
	(*shared.CloudResourceMetadata)(nil),        // 2: org.project_planton.shared.CloudResourceMetadata
	(*GcpArtifactRegistryRepoSpec)(nil),         // 3: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoSpec
	(*GcpArtifactRegistryRepoStackOutputs)(nil), // 4: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoStackOutputs
}
var file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_depIdxs = []int32{
	2, // 0: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepo.metadata:type_name -> org.project_planton.shared.CloudResourceMetadata
	3, // 1: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepo.spec:type_name -> org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoSpec
	1, // 2: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepo.status:type_name -> org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoStatus
	4, // 3: org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoStatus.outputs:type_name -> org.project_planton.provider.gcp.gcpartifactregistryrepo.v1.GcpArtifactRegistryRepoStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_init() }
func file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_init() {
	if File_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto != nil {
		return
	}
	file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_spec_proto_init()
	file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDesc), len(file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto = out.File
	file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_goTypes = nil
	file_org_project_planton_provider_gcp_gcpartifactregistryrepo_v1_api_proto_depIdxs = nil
}
