apiVersion: kubernetes.project-planton.org/v1
kind: Neo4jKubernetes
metadata:
  name: first-neo4j
spec:
  container:
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    isPersistenceEnabled: true
    diskSize: "1Gi"
  memoryConfig:
    heapMax: "512m"
    pageCache: "256m"
  ingress:
    isEnabled: false
