// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: org/project_planton/provider/openfga/openfgastore/v1/api.proto

package openfgastorev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/project-planton/apis/org/project_planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenFgaStore is a deployment component that creates a store in OpenFGA.
//
// A store is the top-level container for authorization data in OpenFGA. Each store
// contains authorization models (which define the relationships and permissions)
// and relationship tuples (which represent the actual authorization data).
//
// IMPORTANT: OpenFGA only has a Terraform provider - there is no Pulumi provider available.
// This component must be deployed using Terraform/Tofu as the provisioner.
// The Pulumi module is a pass-through placeholder that does not create resources.
//
// Use cases:
// - Create isolated authorization stores for different environments (dev/staging/prod)
// - Separate authorization data for different applications or tenants
// - Manage authorization infrastructure as code
//
// Example manifest:
// ```yaml
// apiVersion: openfga.project-planton.org/v1
// kind: OpenFgaStore
// metadata:
//
//	name: production-authz
//	org: my-organization
//	env: production
//
// spec:
//
//	name: production-authorization-store
//
// ```
type OpenFgaStore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api_version is the version of the OpenFGA API resource.
	// Must be "open-fga.project-planton.org/v1" for this version.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// kind is the Kubernetes Resource Model (KRM) kind.
	// Must be "OpenFgaStore" for this resource type.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata contains standard cloud resource metadata.
	// - name: Unique identifier for the store within Project Planton
	// - org: Organization that owns this store
	// - env: Environment (development, staging, production)
	// - labels: Key-value pairs for filtering and organization
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec contains the desired configuration for the OpenFGA store.
	// Currently only the store name is configurable.
	Spec *OpenFgaStoreSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status contains the current state of the OpenFGA store.
	// This is populated by the system after deployment and includes
	// the store ID and other runtime information.
	Status        *OpenFgaStoreStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFgaStore) Reset() {
	*x = OpenFgaStore{}
	mi := &file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFgaStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFgaStore) ProtoMessage() {}

func (x *OpenFgaStore) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFgaStore.ProtoReflect.Descriptor instead.
func (*OpenFgaStore) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *OpenFgaStore) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OpenFgaStore) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OpenFgaStore) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OpenFgaStore) GetSpec() *OpenFgaStoreSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *OpenFgaStore) GetStatus() *OpenFgaStoreStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// OpenFgaStoreStatus represents the current state of an OpenFGA Store resource.
// This is populated by the deployment system and contains read-only outputs.
type OpenFgaStoreStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outputs contains the stack outputs from the OpenFGA store deployment.
	// These values are populated after successful deployment and include
	// the store identifier.
	Outputs       *OpenFgaStoreStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFgaStoreStatus) Reset() {
	*x = OpenFgaStoreStatus{}
	mi := &file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFgaStoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFgaStoreStatus) ProtoMessage() {}

func (x *OpenFgaStoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFgaStoreStatus.ProtoReflect.Descriptor instead.
func (*OpenFgaStoreStatus) Descriptor() ([]byte, []int) {
	return file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *OpenFgaStoreStatus) GetOutputs() *OpenFgaStoreStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_org_project_planton_provider_openfga_openfgastore_v1_api_proto protoreflect.FileDescriptor

const file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDesc = "" +
	"\n" +
	">org/project_planton/provider/openfga/openfgastore/v1/api.proto\x124org.project_planton.provider.openfga.openfgastore.v1\x1a\x1bbuf/validate/validate.proto\x1a?org/project_planton/provider/openfga/openfgastore/v1/spec.proto\x1aHorg/project_planton/provider/openfga/openfgastore/v1/stack_outputs.proto\x1a)org/project_planton/shared/metadata.proto\"\x9d\x03\n" +
	"\fOpenFgaStore\x12G\n" +
	"\vapi_version\x18\x01 \x01(\tB&\xbaH#r!\n" +
	"\x1fopen-fga.project-planton.org/v1R\n" +
	"apiVersion\x12'\n" +
	"\x04kind\x18\x02 \x01(\tB\x13\xbaH\x10r\x0e\n" +
	"\fOpenFgaStoreR\x04kind\x12U\n" +
	"\bmetadata\x18\x03 \x01(\v21.org.project_planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12b\n" +
	"\x04spec\x18\x04 \x01(\v2F.org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12`\n" +
	"\x06status\x18\x05 \x01(\v2H.org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreStatusR\x06status\"~\n" +
	"\x12OpenFgaStoreStatus\x12h\n" +
	"\aoutputs\x18\x01 \x01(\v2N.org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreStackOutputsR\aoutputsB\xa6\x03\n" +
	"8com.org.project_planton.provider.openfga.openfgastore.v1B\bApiProtoP\x01Zmgithub.com/plantonhq/project-planton/apis/org/project_planton/provider/openfga/openfgastore/v1;openfgastorev1\xa2\x02\x05OPPOO\xaa\x023Org.ProjectPlanton.Provider.Openfga.Openfgastore.V1\xca\x023Org\\ProjectPlanton\\Provider\\Openfga\\Openfgastore\\V1\xe2\x02?Org\\ProjectPlanton\\Provider\\Openfga\\Openfgastore\\V1\\GPBMetadata\xea\x028Org::ProjectPlanton::Provider::Openfga::Openfgastore::V1b\x06proto3"

var (
	file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescOnce sync.Once
	file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescData []byte
)

func file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescGZIP() []byte {
	file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescOnce.Do(func() {
		file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDesc), len(file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDesc)))
	})
	return file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDescData
}

var file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_goTypes = []any{
	(*OpenFgaStore)(nil),                 // 0: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStore
	(*OpenFgaStoreStatus)(nil),           // 1: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreStatus
	(*shared.CloudResourceMetadata)(nil), // 2: org.project_planton.shared.CloudResourceMetadata
	(*OpenFgaStoreSpec)(nil),             // 3: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreSpec
	(*OpenFgaStoreStackOutputs)(nil),     // 4: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreStackOutputs
}
var file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_depIdxs = []int32{
	2, // 0: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStore.metadata:type_name -> org.project_planton.shared.CloudResourceMetadata
	3, // 1: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStore.spec:type_name -> org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreSpec
	1, // 2: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStore.status:type_name -> org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreStatus
	4, // 3: org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreStatus.outputs:type_name -> org.project_planton.provider.openfga.openfgastore.v1.OpenFgaStoreStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_init() }
func file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_init() {
	if File_org_project_planton_provider_openfga_openfgastore_v1_api_proto != nil {
		return
	}
	file_org_project_planton_provider_openfga_openfgastore_v1_spec_proto_init()
	file_org_project_planton_provider_openfga_openfgastore_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDesc), len(file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_goTypes,
		DependencyIndexes: file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_depIdxs,
		MessageInfos:      file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_msgTypes,
	}.Build()
	File_org_project_planton_provider_openfga_openfgastore_v1_api_proto = out.File
	file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_goTypes = nil
	file_org_project_planton_provider_openfga_openfgastore_v1_api_proto_depIdxs = nil
}
