.PHONY: up preview destroy refresh

# Run pulumi up
up:
	pulumi up --yes

# Run pulumi preview
preview:
	pulumi preview

# Run pulumi destroy
destroy:
	pulumi destroy --yes

# Run pulumi refresh
refresh:
	pulumi refresh --yes
