apiVersion: aws.project-planton.org/v1
kind: AwsEcrRepo
metadata:
  name: test-aws-ecr-repo
spec:
  vpcCidr: 10.0.0.0/16
  subnetsPerAvailabilityZone: 2
  subnetSize: 12
  availabilityZones:
    - ap-south-1a
    - ap-south-1b
