apiVersion: kubernetes.project.planton/v1
kind: OpenfgaKubernetes
metadata:
  name: test-openfga-server
spec:
  container:
    replicas: 1
    resources:
      limits:
        cpu: 3000m
        memory: 3Gi
      requests:
        cpu: 250m
        memory: 250Mi
  ingress:
    isEnabled: true
    dnsDomain: example.com
  datastore:
    engine: postgres
    uri: postgres://postgres:somepassword@database-hostname:5432/some-database-name?sslmode=disable
