apiVersion: snowflake.project-planton.org/v1
kind: SnowflakeDatabase
metadata:
  name: test-database
  id: snowdb-test-001
  org: engineering
  env: development
  labels:
    team: data-platform
    component: snowflake-database
    managed-by: project-planton
spec:
  # Database name (required)
  name: TEST_DATABASE_DEV
  
  # Database description
  comment: "Test database for development and CI/CD - transient for cost savings"
  
  # Cost optimization: transient database eliminates 7-day Fail-safe period
  is_transient: true
  
  # Minimal Time Travel retention for dev environment (1 day)
  data_retention_time_in_days: 1
  
  # Iceberg configuration (optional)
  catalog: ""
  external_volume: ""
  
  # Collation settings (optional)
  default_ddl_collation: ""
  
  # Schema management
  drop_public_schema_on_creation: false
  
  # Logging and debugging
  enable_console_output: true
  log_level: "INFO"
  trace_level: "ON_EVENT"
  
  # Data management settings
  max_data_extension_time_in_days: 0
  quoted_identifiers_ignore_case: false
  replace_invalid_characters: false
  
  # Storage configuration
  storage_serialization_policy: ""
  
  # Task management settings
  suspend_task_after_num_failures: 5
  task_auto_retry_attempts: 2
  
  # User task configuration
  user_task:
    managed_initial_warehouse_size: "XSMALL"
    minimum_trigger_interval_in_seconds: 60
    timeout_ms: 3600000




