apiVersion: gcp.project-planton.org/v1
kind: GcpDnsZone
metadata:
  name: test.project-planton.org
spec:
  projectId: planton-cloud-dns
  records:
    - recordType: A
      name: test-a.test.project-planton.org.
      values:
        - 1.1.1.3
    - recordType: CNAME
      name: test-cname.test.project-planton.org.
      values:
        - someother.test.project-planton.org.
    - recordType: MX
      name: test.project-planton.org.
      values:
        - 10 alt3.aspmx.l.google.com.
        - 5 alt2.aspmx.l.google.com.
        - 1 aspmx.l.google.com.
        - 5 alt1.aspmx.l.google.com.
        - 10 alt4.aspmx.l.google.com.
    - recordType: TXT
      name: test-txt.test.project-planton.org.
      values:
        - someother.test.project-planton.org.
