// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: project/planton/provider/kubernetes/workload/temporalkubernetes/v1/spec.proto

package temporalkubernetesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	kubernetes "github.com/project-planton/project-planton/apis/project/planton/shared/kubernetes"
	_ "github.com/project-planton/project-planton/apis/project/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// temporal kubernetes database backend enumerates the supported databases.
type TemporalKubernetesDatabaseBackend int32

const (
	// unspecified should not be used
	TemporalKubernetesDatabaseBackend_temporal_kubernetes_database_backend_unspecified TemporalKubernetesDatabaseBackend = 0
	// uses cassandra
	TemporalKubernetesDatabaseBackend_cassandra TemporalKubernetesDatabaseBackend = 1
	// uses postgresql
	TemporalKubernetesDatabaseBackend_postgresql TemporalKubernetesDatabaseBackend = 2
	// uses mysql
	TemporalKubernetesDatabaseBackend_mysql TemporalKubernetesDatabaseBackend = 3
)

// Enum value maps for TemporalKubernetesDatabaseBackend.
var (
	TemporalKubernetesDatabaseBackend_name = map[int32]string{
		0: "temporal_kubernetes_database_backend_unspecified",
		1: "cassandra",
		2: "postgresql",
		3: "mysql",
	}
	TemporalKubernetesDatabaseBackend_value = map[string]int32{
		"temporal_kubernetes_database_backend_unspecified": 0,
		"cassandra":  1,
		"postgresql": 2,
		"mysql":      3,
	}
)

func (x TemporalKubernetesDatabaseBackend) Enum() *TemporalKubernetesDatabaseBackend {
	p := new(TemporalKubernetesDatabaseBackend)
	*p = x
	return p
}

func (x TemporalKubernetesDatabaseBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemporalKubernetesDatabaseBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_enumTypes[0].Descriptor()
}

func (TemporalKubernetesDatabaseBackend) Type() protoreflect.EnumType {
	return &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_enumTypes[0]
}

func (x TemporalKubernetesDatabaseBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemporalKubernetesDatabaseBackend.Descriptor instead.
func (TemporalKubernetesDatabaseBackend) EnumDescriptor() ([]byte, []int) {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP(), []int{0}
}

// temporal kubernetes search attribute type enumerates supported types
type TemporalKubernetesSearchAttributeType int32

const (
	// unspecified should not be used
	TemporalKubernetesSearchAttributeType_temporal_kubernetes_search_attribute_type_unspecified TemporalKubernetesSearchAttributeType = 0
	// keyword type - exact match string (indexed, not analyzed)
	TemporalKubernetesSearchAttributeType_keyword_type TemporalKubernetesSearchAttributeType = 1
	// text type - full-text searchable string (analyzed, only works with Elasticsearch)
	TemporalKubernetesSearchAttributeType_text_type TemporalKubernetesSearchAttributeType = 2
	// int type - 64-bit integer
	TemporalKubernetesSearchAttributeType_int_type TemporalKubernetesSearchAttributeType = 3
	// double type - floating point number
	TemporalKubernetesSearchAttributeType_double_type TemporalKubernetesSearchAttributeType = 4
	// bool type - boolean value
	TemporalKubernetesSearchAttributeType_bool_type TemporalKubernetesSearchAttributeType = 5
	// datetime type - timestamp
	TemporalKubernetesSearchAttributeType_datetime_type TemporalKubernetesSearchAttributeType = 6
	// keyword_list type - array of keywords
	TemporalKubernetesSearchAttributeType_keyword_list_type TemporalKubernetesSearchAttributeType = 7
)

// Enum value maps for TemporalKubernetesSearchAttributeType.
var (
	TemporalKubernetesSearchAttributeType_name = map[int32]string{
		0: "temporal_kubernetes_search_attribute_type_unspecified",
		1: "keyword_type",
		2: "text_type",
		3: "int_type",
		4: "double_type",
		5: "bool_type",
		6: "datetime_type",
		7: "keyword_list_type",
	}
	TemporalKubernetesSearchAttributeType_value = map[string]int32{
		"temporal_kubernetes_search_attribute_type_unspecified": 0,
		"keyword_type":      1,
		"text_type":         2,
		"int_type":          3,
		"double_type":       4,
		"bool_type":         5,
		"datetime_type":     6,
		"keyword_list_type": 7,
	}
)

func (x TemporalKubernetesSearchAttributeType) Enum() *TemporalKubernetesSearchAttributeType {
	p := new(TemporalKubernetesSearchAttributeType)
	*p = x
	return p
}

func (x TemporalKubernetesSearchAttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemporalKubernetesSearchAttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_enumTypes[1].Descriptor()
}

func (TemporalKubernetesSearchAttributeType) Type() protoreflect.EnumType {
	return &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_enumTypes[1]
}

func (x TemporalKubernetesSearchAttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemporalKubernetesSearchAttributeType.Descriptor instead.
func (TemporalKubernetesSearchAttributeType) EnumDescriptor() ([]byte, []int) {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP(), []int{1}
}

// defines a custom search attribute for Temporal workflows
type TemporalKubernetesSearchAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name of the search attribute (e.g., "CustomerId", "Environment")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type of the search attribute
	Type          TemporalKubernetesSearchAttributeType `protobuf:"varint,2,opt,name=type,proto3,enum=project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttributeType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalKubernetesSearchAttribute) Reset() {
	*x = TemporalKubernetesSearchAttribute{}
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalKubernetesSearchAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalKubernetesSearchAttribute) ProtoMessage() {}

func (x *TemporalKubernetesSearchAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalKubernetesSearchAttribute.ProtoReflect.Descriptor instead.
func (*TemporalKubernetesSearchAttribute) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *TemporalKubernetesSearchAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemporalKubernetesSearchAttribute) GetType() TemporalKubernetesSearchAttributeType {
	if x != nil {
		return x.Type
	}
	return TemporalKubernetesSearchAttributeType_temporal_kubernetes_search_attribute_type_unspecified
}

// temporal kubernetes spec defines minimal fields for deploying temporal on kubernetes.
type TemporalKubernetesSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database configuration
	Database *TemporalKubernetesDatabaseConfig `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// disables temporal web ui
	DisableWebUi bool `protobuf:"varint,2,opt,name=disable_web_ui,json=disableWebUi,proto3" json:"disable_web_ui,omitempty"`
	// enables embedded elasticsearch for temporal
	// this is ignored if external elasticsearch is set
	EnableEmbeddedElasticsearch bool `protobuf:"varint,3,opt,name=enableEmbeddedElasticsearch,proto3" json:"enableEmbeddedElasticsearch,omitempty"`
	// enables monitoring stack for temporal
	// enabling this will deploy prometheus and grafana
	EnableMonitoringStack bool `protobuf:"varint,4,opt,name=enableMonitoringStack,proto3" json:"enableMonitoringStack,omitempty"`
	// number of cassandra nodes to be deployed
	// this is only honored when the backend is cassandra, and no external database is provided.
	CassandraReplicas int32 `protobuf:"varint,5,opt,name=cassandraReplicas,proto3" json:"cassandraReplicas,omitempty"`
	// The ingress configuration for the temporal deployment.
	// if enabled, the frontend will be exposed using a load-balancer
	// and also if web ui is enabled it will be exposed using the kubernetes ingress controller.
	Ingress *kubernetes.IngressSpec `protobuf:"bytes,6,opt,name=ingress,proto3" json:"ingress,omitempty"`
	// external elasticsearch configuration to be used by temporal for configuring observability.
	ExternalElasticsearch *TemporalKubernetesExternalElasticsearch `protobuf:"bytes,7,opt,name=external_elasticsearch,json=externalElasticsearch,proto3" json:"external_elasticsearch,omitempty"`
	// custom search attributes to register in the Temporal cluster
	// these attributes can be used to filter and query workflows
	// note: 'text' type only works with Elasticsearch backend
	SearchAttributes []*TemporalKubernetesSearchAttribute `protobuf:"bytes,8,rep,name=search_attributes,json=searchAttributes,proto3" json:"search_attributes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TemporalKubernetesSpec) Reset() {
	*x = TemporalKubernetesSpec{}
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalKubernetesSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalKubernetesSpec) ProtoMessage() {}

func (x *TemporalKubernetesSpec) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalKubernetesSpec.ProtoReflect.Descriptor instead.
func (*TemporalKubernetesSpec) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *TemporalKubernetesSpec) GetDatabase() *TemporalKubernetesDatabaseConfig {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *TemporalKubernetesSpec) GetDisableWebUi() bool {
	if x != nil {
		return x.DisableWebUi
	}
	return false
}

func (x *TemporalKubernetesSpec) GetEnableEmbeddedElasticsearch() bool {
	if x != nil {
		return x.EnableEmbeddedElasticsearch
	}
	return false
}

func (x *TemporalKubernetesSpec) GetEnableMonitoringStack() bool {
	if x != nil {
		return x.EnableMonitoringStack
	}
	return false
}

func (x *TemporalKubernetesSpec) GetCassandraReplicas() int32 {
	if x != nil {
		return x.CassandraReplicas
	}
	return 0
}

func (x *TemporalKubernetesSpec) GetIngress() *kubernetes.IngressSpec {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *TemporalKubernetesSpec) GetExternalElasticsearch() *TemporalKubernetesExternalElasticsearch {
	if x != nil {
		return x.ExternalElasticsearch
	}
	return nil
}

func (x *TemporalKubernetesSpec) GetSearchAttributes() []*TemporalKubernetesSearchAttribute {
	if x != nil {
		return x.SearchAttributes
	}
	return nil
}

// groups database configuration settings.
type TemporalKubernetesDatabaseConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// selected database backend
	Backend TemporalKubernetesDatabaseBackend `protobuf:"varint,1,opt,name=backend,proto3,enum=project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseBackend" json:"backend,omitempty"`
	// external database configuration, if this is not set, in-cluster cassandra would be created
	ExternalDatabase *TemporalKubernetesExternalDatabase `protobuf:"bytes,2,opt,name=external_database,json=externalDatabase,proto3" json:"external_database,omitempty"`
	// primary database or keyspace name
	DatabaseName string `protobuf:"bytes,6,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	// visibility database or keyspace name
	VisibilityName string `protobuf:"bytes,7,opt,name=visibility_name,json=visibilityName,proto3" json:"visibility_name,omitempty"`
	// disables automatic schema creation
	DisableAutoSchemaSetup bool `protobuf:"varint,8,opt,name=disable_auto_schema_setup,json=disableAutoSchemaSetup,proto3" json:"disable_auto_schema_setup,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TemporalKubernetesDatabaseConfig) Reset() {
	*x = TemporalKubernetesDatabaseConfig{}
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalKubernetesDatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalKubernetesDatabaseConfig) ProtoMessage() {}

func (x *TemporalKubernetesDatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalKubernetesDatabaseConfig.ProtoReflect.Descriptor instead.
func (*TemporalKubernetesDatabaseConfig) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *TemporalKubernetesDatabaseConfig) GetBackend() TemporalKubernetesDatabaseBackend {
	if x != nil {
		return x.Backend
	}
	return TemporalKubernetesDatabaseBackend_temporal_kubernetes_database_backend_unspecified
}

func (x *TemporalKubernetesDatabaseConfig) GetExternalDatabase() *TemporalKubernetesExternalDatabase {
	if x != nil {
		return x.ExternalDatabase
	}
	return nil
}

func (x *TemporalKubernetesDatabaseConfig) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *TemporalKubernetesDatabaseConfig) GetVisibilityName() string {
	if x != nil {
		return x.VisibilityName
	}
	return ""
}

func (x *TemporalKubernetesDatabaseConfig) GetDisableAutoSchemaSetup() bool {
	if x != nil {
		return x.DisableAutoSchemaSetup
	}
	return false
}

// describes an external database that temporal can use
type TemporalKubernetesExternalDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hostname for external database
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// port for external database
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// username for database
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// password for database
	Password      string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalKubernetesExternalDatabase) Reset() {
	*x = TemporalKubernetesExternalDatabase{}
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalKubernetesExternalDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalKubernetesExternalDatabase) ProtoMessage() {}

func (x *TemporalKubernetesExternalDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalKubernetesExternalDatabase.ProtoReflect.Descriptor instead.
func (*TemporalKubernetesExternalDatabase) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *TemporalKubernetesExternalDatabase) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TemporalKubernetesExternalDatabase) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TemporalKubernetesExternalDatabase) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TemporalKubernetesExternalDatabase) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// describes an external elasticsearch cluster that temporal can use
// for advanced visibility instead of deploying an in-cluster es chart.
type TemporalKubernetesExternalElasticsearch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the host address of the existing elasticsearch cluster
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// the port for the existing elasticsearch cluster
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// optional username, if the external cluster requires auth
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// optional password, if the external cluster requires auth
	Password      string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalKubernetesExternalElasticsearch) Reset() {
	*x = TemporalKubernetesExternalElasticsearch{}
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalKubernetesExternalElasticsearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalKubernetesExternalElasticsearch) ProtoMessage() {}

func (x *TemporalKubernetesExternalElasticsearch) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalKubernetesExternalElasticsearch.ProtoReflect.Descriptor instead.
func (*TemporalKubernetesExternalElasticsearch) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP(), []int{4}
}

func (x *TemporalKubernetesExternalElasticsearch) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TemporalKubernetesExternalElasticsearch) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TemporalKubernetesExternalElasticsearch) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TemporalKubernetesExternalElasticsearch) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto protoreflect.FileDescriptor

const file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDesc = "" +
	"\n" +
	"Mproject/planton/provider/kubernetes/workload/temporalkubernetes/v1/spec.proto\x12Bproject.planton.provider.kubernetes.workload.temporalkubernetes.v1\x1a\x1bbuf/validate/validate.proto\x1a2project/planton/shared/kubernetes/kubernetes.proto\x1a,project/planton/shared/options/options.proto\"\xc7\x01\n" +
	"!TemporalKubernetesSearchAttribute\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12\x85\x01\n" +
	"\x04type\x18\x02 \x01(\x0e2i.project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttributeTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\"\xfa\x05\n" +
	"\x16TemporalKubernetesSpec\x12\x88\x01\n" +
	"\bdatabase\x18\x01 \x01(\v2d.project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseConfigB\x06\xbaH\x03\xc8\x01\x01R\bdatabase\x12$\n" +
	"\x0edisable_web_ui\x18\x02 \x01(\bR\fdisableWebUi\x12@\n" +
	"\x1benableEmbeddedElasticsearch\x18\x03 \x01(\bR\x1benableEmbeddedElasticsearch\x124\n" +
	"\x15enableMonitoringStack\x18\x04 \x01(\bR\x15enableMonitoringStack\x123\n" +
	"\x11cassandraReplicas\x18\x05 \x01(\x05B\x05\x8a\xa6\x1d\x011R\x11cassandraReplicas\x12H\n" +
	"\aingress\x18\x06 \x01(\v2..project.planton.shared.kubernetes.IngressSpecR\aingress\x12\xa2\x01\n" +
	"\x16external_elasticsearch\x18\a \x01(\v2k.project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesExternalElasticsearchR\x15externalElasticsearch\x12\x92\x01\n" +
	"\x11search_attributes\x18\b \x03(\v2e.project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttributeR\x10searchAttributes\"\xf2\x03\n" +
	" TemporalKubernetesDatabaseConfig\x12\x87\x01\n" +
	"\abackend\x18\x01 \x01(\x0e2e.project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseBackendB\x06\xbaH\x03\xc8\x01\x01R\abackend\x12\x93\x01\n" +
	"\x11external_database\x18\x02 \x01(\v2f.project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesExternalDatabaseR\x10externalDatabase\x121\n" +
	"\rdatabase_name\x18\x06 \x01(\tB\f\x8a\xa6\x1d\btemporalR\fdatabaseName\x12@\n" +
	"\x0fvisibility_name\x18\a \x01(\tB\x17\x8a\xa6\x1d\x13temporal_visibilityR\x0evisibilityName\x129\n" +
	"\x19disable_auto_schema_setup\x18\b \x01(\bR\x16disableAutoSchemaSetup\"\x84\x01\n" +
	"\"TemporalKubernetesExternalDatabase\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x81\x01\n" +
	"'TemporalKubernetesExternalElasticsearch\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword*\x83\x01\n" +
	"!TemporalKubernetesDatabaseBackend\x124\n" +
	"0temporal_kubernetes_database_backend_unspecified\x10\x00\x12\r\n" +
	"\tcassandra\x10\x01\x12\x0e\n" +
	"\n" +
	"postgresql\x10\x02\x12\t\n" +
	"\x05mysql\x10\x03*\xdb\x01\n" +
	"%TemporalKubernetesSearchAttributeType\x129\n" +
	"5temporal_kubernetes_search_attribute_type_unspecified\x10\x00\x12\x10\n" +
	"\fkeyword_type\x10\x01\x12\r\n" +
	"\ttext_type\x10\x02\x12\f\n" +
	"\bint_type\x10\x03\x12\x0f\n" +
	"\vdouble_type\x10\x04\x12\r\n" +
	"\tbool_type\x10\x05\x12\x11\n" +
	"\rdatetime_type\x10\x06\x12\x15\n" +
	"\x11keyword_list_type\x10\aB\x8e\x04\n" +
	"Fcom.project.planton.provider.kubernetes.workload.temporalkubernetes.v1B\tSpecProtoP\x01Z\x87\x01github.com/project-planton/project-planton/apis/project/planton/provider/kubernetes/workload/temporalkubernetes/v1;temporalkubernetesv1\xa2\x02\x06PPPKWT\xaa\x02BProject.Planton.Provider.Kubernetes.Workload.Temporalkubernetes.V1\xca\x02BProject\\Planton\\Provider\\Kubernetes\\Workload\\Temporalkubernetes\\V1\xe2\x02NProject\\Planton\\Provider\\Kubernetes\\Workload\\Temporalkubernetes\\V1\\GPBMetadata\xea\x02HProject::Planton::Provider::Kubernetes::Workload::Temporalkubernetes::V1b\x06proto3"

var (
	file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescOnce sync.Once
	file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescData []byte
)

func file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescGZIP() []byte {
	file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescOnce.Do(func() {
		file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDesc), len(file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDesc)))
	})
	return file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDescData
}

var file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_goTypes = []any{
	(TemporalKubernetesDatabaseBackend)(0),          // 0: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseBackend
	(TemporalKubernetesSearchAttributeType)(0),      // 1: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttributeType
	(*TemporalKubernetesSearchAttribute)(nil),       // 2: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttribute
	(*TemporalKubernetesSpec)(nil),                  // 3: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSpec
	(*TemporalKubernetesDatabaseConfig)(nil),        // 4: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseConfig
	(*TemporalKubernetesExternalDatabase)(nil),      // 5: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesExternalDatabase
	(*TemporalKubernetesExternalElasticsearch)(nil), // 6: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesExternalElasticsearch
	(*kubernetes.IngressSpec)(nil),                  // 7: project.planton.shared.kubernetes.IngressSpec
}
var file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_depIdxs = []int32{
	1, // 0: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttribute.type:type_name -> project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttributeType
	4, // 1: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSpec.database:type_name -> project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseConfig
	7, // 2: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSpec.ingress:type_name -> project.planton.shared.kubernetes.IngressSpec
	6, // 3: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSpec.external_elasticsearch:type_name -> project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesExternalElasticsearch
	2, // 4: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSpec.search_attributes:type_name -> project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesSearchAttribute
	0, // 5: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseConfig.backend:type_name -> project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseBackend
	5, // 6: project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesDatabaseConfig.external_database:type_name -> project.planton.provider.kubernetes.workload.temporalkubernetes.v1.TemporalKubernetesExternalDatabase
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() {
	file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_init()
}
func file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_init() {
	if File_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDesc), len(file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_goTypes,
		DependencyIndexes: file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_depIdxs,
		EnumInfos:         file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_enumTypes,
		MessageInfos:      file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_msgTypes,
	}.Build()
	File_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto = out.File
	file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_goTypes = nil
	file_project_planton_provider_kubernetes_workload_temporalkubernetes_v1_spec_proto_depIdxs = nil
}
