---
apiVersion: aws.project-planton.org/v1
kind: AwsIamRole
metadata:
  name: "{{ values.env }}-eks-cluster-role"
spec:
  description: IAM role for EKS control plane
  managedPolicyArns:
    - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  trustPolicy:
    Statement:
      - Effect: Allow
        Principal:
          Service: eks.amazonaws.com
        Action: sts:AssumeRole
    Version: "2012-10-17"
---
apiVersion: aws.project-planton.org/v1
kind: AwsIamRole
metadata:
  name: "{{ values.env }}-eks-node-role"
spec:
  description: IAM role for EKS worker nodes
  managedPolicyArns:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  trustPolicy:
    Statement:
      - Effect: Allow
        Principal:
          Service: ec2.amazonaws.com
        Action: sts:AssumeRole
    Version: "2012-10-17"
