---
apiVersion: aws.project-planton.org/v1
kind: AwsEksNodeGroup
metadata:
  name: "{{ values.node_group_name }}"
spec:
  clusterName:
    valueFrom:
      kind: AwsEksCluster
      name: "{{ values.cluster_name }}"
      fieldPath: metadata.name
  nodeRoleArn:
    valueFrom:
      kind: AwsIamRole
      name: "{{ values.env }}-eks-node-role"
      fieldPath: status.outputs.roleArn
  subnetIds:
    - valueFrom:
        kind: AwsVpc
        name: "{{ values.env }}-vpc"
        fieldPath: status.outputs.privateSubnets.[0].id
    - valueFrom:
        kind: AwsVpc
        name: "{{ values.env }}-vpc"
        fieldPath: status.outputs.privateSubnets.[1].id
  instanceType: "{{ values.node_instance_type }}"
  scaling:
    minSize: {{ values.node_min_size }}
    maxSize: {{ values.node_max_size }}
    desiredSize: {{ values.node_desired_size }}
  capacityType: "{{ values.node_capacity_type }}"
  diskSizeGb: {{ values.node_disk_size_gb }}
  {% if values.node_ssh_key_name != "" %}
  sshKeyName: "{{ values.node_ssh_key_name }}"
  {% endif %}
  labels:
    pool: "{{ values.node_group_name }}"
