// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: project/planton/provider/gcp/gcpcloudfunction/v1/stack_input.proto

package gcpcloudfunctionv1

import (
	v1 "github.com/project-planton/project-planton/apis/project/planton/credential/gcpcredential/v1"
	shared "github.com/project-planton/project-planton/apis/project/planton/shared"
	pulumi "github.com/project-planton/project-planton/apis/project/planton/shared/iac/pulumi"
	terraform "github.com/project-planton/project-planton/apis/project/planton/shared/iac/terraform"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// gcp-cloud-function stack-input
type GcpCloudFunctionStackInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// iac-provisioner
	Provisioner shared.IacProvisioner `protobuf:"varint,1,opt,name=provisioner,proto3,enum=project.planton.shared.IacProvisioner" json:"provisioner,omitempty"`
	// pulumi input required when the provisioner is pulumi
	Pulumi *pulumi.PulumiStackInfo `protobuf:"bytes,2,opt,name=pulumi,proto3" json:"pulumi,omitempty"`
	// terraform input required when the provisioner is terraform
	Terraform *terraform.TerraformStackInfo `protobuf:"bytes,3,opt,name=terraform,proto3" json:"terraform,omitempty"`
	// target cloud-resource
	Target *GcpCloudFunction `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// provider-credential
	ProviderCredential *v1.GcpCredentialSpec `protobuf:"bytes,5,opt,name=provider_credential,json=providerCredential,proto3" json:"provider_credential,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GcpCloudFunctionStackInput) Reset() {
	*x = GcpCloudFunctionStackInput{}
	mi := &file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpCloudFunctionStackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpCloudFunctionStackInput) ProtoMessage() {}

func (x *GcpCloudFunctionStackInput) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpCloudFunctionStackInput.ProtoReflect.Descriptor instead.
func (*GcpCloudFunctionStackInput) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDescGZIP(), []int{0}
}

func (x *GcpCloudFunctionStackInput) GetProvisioner() shared.IacProvisioner {
	if x != nil {
		return x.Provisioner
	}
	return shared.IacProvisioner(0)
}

func (x *GcpCloudFunctionStackInput) GetPulumi() *pulumi.PulumiStackInfo {
	if x != nil {
		return x.Pulumi
	}
	return nil
}

func (x *GcpCloudFunctionStackInput) GetTerraform() *terraform.TerraformStackInfo {
	if x != nil {
		return x.Terraform
	}
	return nil
}

func (x *GcpCloudFunctionStackInput) GetTarget() *GcpCloudFunction {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GcpCloudFunctionStackInput) GetProviderCredential() *v1.GcpCredentialSpec {
	if x != nil {
		return x.ProviderCredential
	}
	return nil
}

var File_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto protoreflect.FileDescriptor

const file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDesc = "" +
	"\n" +
	"Bproject/planton/provider/gcp/gcpcloudfunction/v1/stack_input.proto\x120project.planton.provider.gcp.gcpcloudfunction.v1\x1a6project/planton/credential/gcpcredential/v1/spec.proto\x1a:project/planton/provider/gcp/gcpcloudfunction/v1/api.proto\x1a.project/planton/shared/iac/pulumi/pulumi.proto\x1a project/planton/shared/iac.proto\x1a4project/planton/shared/iac/terraform/terraform.proto\"\xd7\x03\n" +
	"\x1aGcpCloudFunctionStackInput\x12H\n" +
	"\vprovisioner\x18\x01 \x01(\x0e2&.project.planton.shared.IacProvisionerR\vprovisioner\x12J\n" +
	"\x06pulumi\x18\x02 \x01(\v22.project.planton.shared.iac.pulumi.PulumiStackInfoR\x06pulumi\x12V\n" +
	"\tterraform\x18\x03 \x01(\v28.project.planton.shared.iac.terraform.TerraformStackInfoR\tterraform\x12Z\n" +
	"\x06target\x18\x04 \x01(\v2B.project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunctionR\x06target\x12o\n" +
	"\x13provider_credential\x18\x05 \x01(\v2>.project.planton.credential.gcpcredential.v1.GcpCredentialSpecR\x12providerCredentialB\xa3\x03\n" +
	"4com.project.planton.provider.gcp.gcpcloudfunction.v1B\x0fStackInputProtoP\x01Zsgithub.com/project-planton/project-planton/apis/project/planton/provider/gcp/gcpcloudfunction/v1;gcpcloudfunctionv1\xa2\x02\x05PPPGG\xaa\x020Project.Planton.Provider.Gcp.Gcpcloudfunction.V1\xca\x020Project\\Planton\\Provider\\Gcp\\Gcpcloudfunction\\V1\xe2\x02<Project\\Planton\\Provider\\Gcp\\Gcpcloudfunction\\V1\\GPBMetadata\xea\x025Project::Planton::Provider::Gcp::Gcpcloudfunction::V1b\x06proto3"

var (
	file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDescOnce sync.Once
	file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDescData []byte
)

func file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDescGZIP() []byte {
	file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDescOnce.Do(func() {
		file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDesc), len(file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDesc)))
	})
	return file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDescData
}

var file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_goTypes = []any{
	(*GcpCloudFunctionStackInput)(nil),   // 0: project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunctionStackInput
	(shared.IacProvisioner)(0),           // 1: project.planton.shared.IacProvisioner
	(*pulumi.PulumiStackInfo)(nil),       // 2: project.planton.shared.iac.pulumi.PulumiStackInfo
	(*terraform.TerraformStackInfo)(nil), // 3: project.planton.shared.iac.terraform.TerraformStackInfo
	(*GcpCloudFunction)(nil),             // 4: project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunction
	(*v1.GcpCredentialSpec)(nil),         // 5: project.planton.credential.gcpcredential.v1.GcpCredentialSpec
}
var file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_depIdxs = []int32{
	1, // 0: project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunctionStackInput.provisioner:type_name -> project.planton.shared.IacProvisioner
	2, // 1: project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunctionStackInput.pulumi:type_name -> project.planton.shared.iac.pulumi.PulumiStackInfo
	3, // 2: project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunctionStackInput.terraform:type_name -> project.planton.shared.iac.terraform.TerraformStackInfo
	4, // 3: project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunctionStackInput.target:type_name -> project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunction
	5, // 4: project.planton.provider.gcp.gcpcloudfunction.v1.GcpCloudFunctionStackInput.provider_credential:type_name -> project.planton.credential.gcpcredential.v1.GcpCredentialSpec
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_init() }
func file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_init() {
	if File_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto != nil {
		return
	}
	file_project_planton_provider_gcp_gcpcloudfunction_v1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDesc), len(file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_goTypes,
		DependencyIndexes: file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_depIdxs,
		MessageInfos:      file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_msgTypes,
	}.Build()
	File_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto = out.File
	file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_goTypes = nil
	file_project_planton_provider_gcp_gcpcloudfunction_v1_stack_input_proto_depIdxs = nil
}
