{% if values.create_dns_zone | bool %}
---
apiVersion: digital-ocean.project-planton.org/v1
kind: DigitalOceanDnsZone
metadata:
  name: "{{ values.domain_name }}"
spec:
  domainName: "{{ values.domain_name }}"
  {% endif %}
