apiVersion: aws.project-planton.org/v1
kind: AwsDynamodb
metadata:
  name: awsdynamodb-demo
spec:
  billingMode: BILLING_MODE_PAY_PER_REQUEST
  attributeDefinitions:
    - name: pk
      type: ATTRIBUTE_TYPE_S
  keySchema:
    - attributeName: pk
      keyType: KEY_TYPE_HASH
  # ttl:
  #   enabled: false
  #   attributeName: ""
  # streamEnabled: false
  # streamViewType: STREAM_VIEW_TYPE_UNSPECIFIED
  # pointInTimeRecoveryEnabled: false
  # serverSideEncryption:
  #   enabled: false
  #   kmsKeyArn: ""
  # tableClass: TABLE_CLASS_UNSPECIFIED
  # deletionProtectionEnabled: false
  # contributorInsightsEnabled: false


