apiVersion: kubernetes.project-planton.org/v1
kind: PostgresKubernetes
metadata:
  name: test-postgres-database
spec:
  container:
    replicas: 1
    resources:
      limits:
        cpu: 3000m
        memory: 3Gi
      requests:
        cpu: 250m
        memory: 250Mi
    diskSize: 1Gi
  ingress:
    isEnabled: true
    dnsDomain: example.com
