apiVersion: azure.project-planton.org/v1
kind: AzureVpc
metadata:
  name: test-vpc
  org: test-org
  env: dev
spec:
  address_space_cidr: "10.99.0.0/16"
  nodes_subnet_cidr: "10.99.0.0/18"
  is_nat_gateway_enabled: true
  tags:
    test: "true"

