apiVersion: kubernetes.project-planton.org/v1
kind: ClickhouseKubernetes
metadata:
  name: clickhousekubernetes-demo
spec:
  container:
    replicas: 1
    isPersistenceEnabled: true
    diskSize: 8Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 2Gi
