.PHONY: preview
preview:
	project-planton pulumi preview --manifest $(manifest)

.PHONY: up
up:
	project-planton pulumi up --manifest $(manifest)

.PHONY: down
down:
	project-planton pulumi down --manifest $(manifest)

.PHONY: refresh
refresh:
	project-planton pulumi refresh --manifest $(manifest)

