// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: project/planton/provider/civo/civoloadbalancer/v1/stack_outputs.proto

package civoloadbalancerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CivoLoadBalancerStackOutputs captures the outputs after provisioning a Civo Load Balancer.
type CivoLoadBalancerStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the created Civo Load Balancer.
	LoadBalancerId string `protobuf:"bytes,1,opt,name=load_balancer_id,json=loadBalancerId,proto3" json:"load_balancer_id,omitempty"`
	// The public IP address assigned to the Load Balancer.
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// The DNS name for the Load Balancer (if applicable).
	DnsName string `protobuf:"bytes,3,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	// The creation timestamp of the Load Balancer in RFC 3339 format.
	CreatedAtRfc3339 string `protobuf:"bytes,4,opt,name=created_at_rfc3339,json=createdAtRfc3339,proto3" json:"created_at_rfc3339,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CivoLoadBalancerStackOutputs) Reset() {
	*x = CivoLoadBalancerStackOutputs{}
	mi := &file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CivoLoadBalancerStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CivoLoadBalancerStackOutputs) ProtoMessage() {}

func (x *CivoLoadBalancerStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CivoLoadBalancerStackOutputs.ProtoReflect.Descriptor instead.
func (*CivoLoadBalancerStackOutputs) Descriptor() ([]byte, []int) {
	return file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *CivoLoadBalancerStackOutputs) GetLoadBalancerId() string {
	if x != nil {
		return x.LoadBalancerId
	}
	return ""
}

func (x *CivoLoadBalancerStackOutputs) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CivoLoadBalancerStackOutputs) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

func (x *CivoLoadBalancerStackOutputs) GetCreatedAtRfc3339() string {
	if x != nil {
		return x.CreatedAtRfc3339
	}
	return ""
}

var File_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"Eproject/planton/provider/civo/civoloadbalancer/v1/stack_outputs.proto\x121project.planton.provider.civo.civoloadbalancer.v1\"\xb0\x01\n" +
	"\x1cCivoLoadBalancerStackOutputs\x12(\n" +
	"\x10load_balancer_id\x18\x01 \x01(\tR\x0eloadBalancerId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x19\n" +
	"\bdns_name\x18\x03 \x01(\tR\adnsName\x12,\n" +
	"\x12created_at_rfc3339\x18\x04 \x01(\tR\x10createdAtRfc3339B\xab\x03\n" +
	"5com.project.planton.provider.civo.civoloadbalancer.v1B\x11StackOutputsProtoP\x01Ztgithub.com/project-planton/project-planton/apis/project/planton/provider/civo/civoloadbalancer/v1;civoloadbalancerv1\xa2\x02\x05PPPCC\xaa\x021Project.Planton.Provider.Civo.Civoloadbalancer.V1\xca\x021Project\\Planton\\Provider\\Civo\\Civoloadbalancer\\V1\xe2\x02=Project\\Planton\\Provider\\Civo\\Civoloadbalancer\\V1\\GPBMetadata\xea\x026Project::Planton::Provider::Civo::Civoloadbalancer::V1b\x06proto3"

var (
	file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDescData []byte
)

func file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDesc), len(file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDesc)))
	})
	return file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDescData
}

var file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_goTypes = []any{
	(*CivoLoadBalancerStackOutputs)(nil), // 0: project.planton.provider.civo.civoloadbalancer.v1.CivoLoadBalancerStackOutputs
}
var file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_init() }
func file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_init() {
	if File_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDesc), len(file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto = out.File
	file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_goTypes = nil
	file_project_planton_provider_civo_civoloadbalancer_v1_stack_outputs_proto_depIdxs = nil
}
