apiVersion: kubernetes.project-planton.org/v1
kind: RedisKubernetes
metadata:
  name: test-redis-database
spec:
  container:
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    isPersistenceEnabled: true
    diskSize: 1Gi
  ingress:
    enabled: true
    hostname: test-redis-database.example.com
